### ISSUE TITLE
assigning swarm labels when running docker-machine create?

### ISSUE THREAD

**Issue by cboettig** [docker/machine#1002]
The integration of `docker-machine` with `swarm` through a handful of simple flags is just awesome.  The tutorial on using docker swarm that you have in the docker-machine docs is far easier than anything Google gives me on docker swarm tutorials, which really highlights just what a win docker-machine is.  Nice work!

However, it's not obvious how one goes about adding labels for swarm constraints. It looks like these labels need to be added when starting the docker daemon, so I don't see how to run them once machine has already brought up the docker daemon to begin with.

Also, perhaps some of these labels can be or are being added automatically, but I don't see how to discover what these are.  

Sorry if I'm just not understanding how this is supposed to work.

**Comment by nathanleclaire** [comment]
Hey @cboettig.  Thanks for the praise!

If I understand correctly, you're interested in setting labels for the daemon so that you can selectively schedule on daemons?

That should be covered by https://github.com/docker/machine/issues/974 in the 0.3.0 release.

Until then, if you just want to play around, you could always just manually edit the relevant file (for instance, `/etc/default/docker` on Ubuntu systems) to have the flags you desire, and re-start the daemon.

**Comment by cboettig** [comment]
#974 looks awesome, thanks for the link!
