### ISSUE TITLE
Help Output

### ISSUE THREAD

**Issue by UserTaken** [docker/machine#1014]
`Docker` commands are organized alphabetically while there is no clear order to how `Docker Machine` commands are listed. The options for `Docker Machine` is listed below commands while options for `Docker` and `Docker Compose` are listed above. The `-v` option is redundant if version number is displayed by default. 

```
Usage: docker-machine [OPTIONS] COMMAND [arg...]

Create and manage machines running Docker.

Options:
   -D, --debug					Enable debug mode
   -h, --help=false				Print usage
   --storage-path	            Configures storage path [$MACHINE_STORAGE_PATH]
   --tls-ca-cert				CA to verify remotes against [$MACHINE_TLS_CA_CERT]
   --tls-ca-key					Private key to generate certificates [$MACHINE_TLS_CA_KEY]
   --tls-client-cert			Client cert to use for TLS [$MACHINE_TLS_CLIENT_CERT]
   --tls-client-key				Private key used in client TLS auth [$MACHINE_TLS_CLIENT_KEY]
   -v, --version=false			Print version information and quit

Commands:
   active						Get or set the active machine
   create						Create a machine
   config						Print the connection config for machine
   env							Display the commands to set up the environment for the Docker client
   inspect						Inspect information about a machine
   ip							Get the IP address of a machine
   kill							Kill a machine
   ls							List machines
   regenerate-certs				Regenerate TLS Certificates for a machine
   restart						Restart a machine
   rm							Remove a machine
   ssh							Log into or run a command on a machine with SSH
   start						Start a machine
   stop							Stop a machine
   upgrade						Upgrade a machine to the latest version of Docker
   url							Get the URL of a machine

Run 'docker-machine COMMAND --help' for more information on a command.
```

**Comment by thaJeztah** [comment]
> The -v option is redundant if version number is displayed by default.

At this point, perhaps, but having a `-v` is good because a) people expect it b) it allows to change the default output (no flags) and still have a way to get the version output.

I'm +1 for being consistent between the projects, so alphabetically and same order of flags/commands

**Comment by hairyhenderson** [comment]
@UserTaken - Not hard to alphabetize _most_ of the commands, but we're somewhat constrained by our use of `codegangsta/cli` to handle this stuff for us. In particular, the `help, h` option is added for us automatically so it always ends up at the bottom.

Personally I like `help` being at the bottom, because it draws attention to it, which can be useful at a glance (people tend to scan the stuff at the top & bottom before reading the middle content in-depth).

I'll submit a PR to re-order the rest of the commands, though, since it's a simple fix.

I would imagine that harmonizing the rest of the stuff with `docker` and `docker-compose` would require all of the projects to standardize on a CLI framework (difficult, since `docker-compose` is written in a different language from the other two). I will mention that `swarm` also uses `codegangsta/cli`.

/cc @ehazlett @nathanleclaire

**Comment by UserTaken** [comment]
@hairyhenderson Since `-h, --help` is already in the options category like Docker, how about removing it from the commands  category and instead add a note at the bottom as Docker does. The explanation for options such as `-h, --help=false` is different between the projects. Also the capitalization  and wording such as `COMMANDS` vs `Commands` and `GLOBAL OPTIONS` vs `Options`.

**Comment by hairyhenderson** [comment]
@UserTaken - Ok, I think most of those things can be altered - will have a stab at it in separate PRs.

**Comment by hairyhenderson** [comment]
@UserTaken - I think I've almost addressed all of this issue ;)

I think this issue is about 3 different things:
1. the general format of the usage message (capitalization, order, names)
2. sorting of commands
3. removing the `help` command from the listing, and leaving `--help`.

I've accomplished 1 and 2 in #1059 and #1065, which leaves 3. I looked into it and it's going to be difficult without some changes to `codegangsta/cli`.

**Comment by UserTaken** [comment]
@hairyhenderson
I just compiled Machine with #1065 and noticed that the spacing off. Beyond that, some things things that can be adjusted include matching the explanation of an option with Docker, and listing the option the short syntax first.

 `--version, -v                     print the version` 
vs
`-v, --version=false          Print version information and quit`

**Comment by nathanleclaire** [comment]
Hi @UserTaken, I am pretty happy with what we have now but feel free to open a more specific issue if you feel like it could be further improved.
