### ISSUE TITLE
docker-machine upgrade fails if VM is powered off

### ISSUE THREAD

**Issue by jeffdm** [docker/machine#1019]
```
DEBU[0000] command=upgrade machine=dev                  
DEBU[0000] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=30 -o LogLevel=quiet -p 53023 -i /Users/<username>/.docker/machine/machines/dev/id_rsa docker@localhost cat /etc/os-release 
ERRO[0029] Error running SSH command to get /etc/os-release: exit status 255 
```

Because it relies on SSH access to read /etc/os-release. Low priority since for Kitematic we can just attempt to upgrade after starting the VM.

Before this we've been directly reading the `boot2docker.iso` file which has the version encoded as a string somewhere as `Boot2Docker-x.x.x`. This is a hack, but worked offline. Is there a reliable way to inspect the `os-release` file from the iso directly?

**Comment by ehazlett** [comment]
@jeffdm thanks -- we could perhaps check for that.  i think if it's virtualbox we could probably safely ignore this check and just skip the stop of the VM and proceed with the upgrade.

@nathanleclaire thoughts?

**Comment by nathanleclaire** [comment]
In the future we will not necessarily know what OS a stopped machine is running, and we need to know that in order to know how to proceed on an upgrade.  Additionally it is unique to b2d that it can be upgraded while stopped, Ubuntu for instance has to be running.

So I think we should either require the machine be running to perform an upgrade, or run the start command ourselves before we go forward with the upgrade.

**Comment by jeffdm** [comment]
That makes sense! I had forgotten about the cloud providers. I think a good solution is just to spit out an error if it's stopped

**Comment by ehazlett** [comment]
Closing as #1133 is merged.

**Comment by jeffdm** [comment]
Woo! Awesome. Thanks!
