### ISSUE TITLE
Revert `env` command to former output.

### ISSUE THREAD

**Issue by haihappen** [docker/machine#1038]
With the version prior to `0.2.0` I was able to run `$(machine env)` on my ZSH, however the recent changes result in following error:
```
export: not valid in this context: shell:
```

Any chance to get the old behaviour back?

**Comment by RickWieman** [comment]
That's something I noticed as well, unfortunately.
It *does* work if you use `eval "$(docker-machine env)"`, though.

**Comment by haihappen** [comment]
Yes, however this more to type :stuck_out_tongue: 
This was my workflow:

```sh
machine env # Prints the output to check.
$(!!) # Executes the last command and evals it.
```

**Comment by hairyhenderson** [comment]
@haihappen - Sorry about this! This was changed in the 0.2.0 release. See #795 for background on the rationale. All of our documentation _should_ mention the `eval "$(docker-machine env}"` syntax now, too.

And, while it _would've_ worked without `eval` in the past, because of #783, it can't anymore.
