### ISSUE TITLE
Google auth failures bork docker-machine, and clarify docs?

### ISSUE THREAD

**Issue by cboettig** [docker/machine#1061]
Hi Docker-machine devs,

Very much enjoying docker machine; but having a few hiccups on using it with the Google Compute Engine.  Maybe you could clarify the definitions of the a few of the command-line arguments?

- `--google-project` Is this the user-created 'name' of the project, or the (globally unique) `id` of the project?  (Or the OAuth Client ID?)

- `--google-auth-token` Is this the OAuth secret token, the client token, or an option that should be ignored all-together (e.g. in favor of the browser-based authentication)?

Also, I have found that if authentication fails, `docker-machine` enters an unusable state, wherein even a command like `docker-machine ls` gives me the Google OAuth dialog (twice). If I attempt to authenticate, I get a fatal error (`FATA[0026] Token exchange error: OAuthError: updateToken: Unexpected HTTP status 400 Bad Request `) and thus cannot run `docker-machine rm` or `docker-machine ls` or any other such command.

I had to manually clean out `~/.docker/machine/machines` in order to recover a functional `docker-machine` prompt, which is obviously not ideal...  

Thanks!  I realize this is probably more my ignorance than your fault; but any pointers would be much appreciated.

**Comment by nathanleclaire** [comment]
cc @jeffmendoza

**Comment by cboettig** [comment]
- It appears that `--google-project` is the (globally unique) project id, not the project name (At least using these terms as they appear on the google web interface; it does seem that the gcloud SDK tool also has the habit of referring to this unique id as a 'project name' instead of the 'project id', so perhaps the confusion is not on docker-machine's side ;-))

- It also appears that `auth-token` isn't needed when authenticating interactively, (though it's unclear how this option should be used.  Does this mean that the automated token returned in the web interaction can be reused?)

Other than these minor documentation confusions, it's really just the auth-error behavior that is most annoying.

**Comment by jeffmendoza** [comment]
@cboettig Yes, the docs could be clarified, looks like they are here: https://github.com/docker/machine/blob/master/docs/index.md#google-compute-engine

@nathanleclaire Is this expected? When a driver is returning an error for getting status on a machine, shouldn't machine ls and machine rm work? Maybe you need rm -f?

**Comment by nathanleclaire** [comment]
> Is this expected? When a driver is returning an error for getting status on a machine, shouldn't machine ls and machine rm work? Maybe you need rm -f?

No, errors with machines should _never_ lock those commands up, so if they are, it's definitely a bug.

@jeffmendoza Do you know if we can replace this manual-style auth with a token based one (i.e. instead of prompting the user for confirmation during the create we get them to set up a few secrets they pass in at create time)?  I'm not too familiar with GCE unfortunately.  The way the driver currently works makes it difficult to automate.

**Comment by nathanleclaire** [comment]
`docker-machine rm -f` should work to clean up the local reference though.

**Comment by jeffmendoza** [comment]
I believe thew `auth-token` option is for automated auth. I need to look into it.

**Comment by DazWilkin** [comment]
I'm unable to create a machine on GCE using --google-auth-token parameter. The docker-machine create command prompts for the user consent flow regardless.

A good model for the implementation of the auth model for GCE driver is Google's gcloud CLI. Using gcloud, once a user's account is authenticated, its credentials are persisted, do not expire and the auth tokens are seamlessly used across ensuing command invocations.

https://cloud.google.com/sdk/gcloud/#gcloud.auth


Full disclosure: I'm a Google employee in cloud but not a developer

**Comment by jayfk** [comment]
@DazWilkin Can this be limited to only authenticate for the google compute engine, or is this a global authentication mechanism for the whole google account?

**Comment by DazWilkin** [comment]
A Google account is authenticated against all Google services but the authorization is constrained by the use of scopes. It's possible to authorize only for Compute Engine and then for read-write<sup>1</sup> or read-only<sup>2</sup> on Compute Engine methods:

<sup>1</sup>https://www.googleapis.com/auth/compute
<sup>2</sup>https://www.googleapis.com/auth/compute.readonly

I suspect, the scopes should be user-tailorable and part of any auth flow so that the scope<sup>3</sup> for full access to Google Cloud Platform services, for example, could be granted.

<sup>3</sup>https://www.googleapis.com/auth/cloud-platform

**Comment by yonah-codefresh** [comment]
Any progress on this? Is there any way to create machines with the google driver non-interactively?

**Comment by dgageot** [comment]
@cboettig With version 0.5.0, `--google-auth-token` is not supported anymore. Instead, it used Google's Default Authentication so that you just have to run `gcloud auth login` once and then use `docker-machine` as many times as you like.

Error messages should also be a bit clearer and

@cboettig Documentation was updated to replace "Projec" name" with "Project Id"

Closing the ticket. Feel free to reopen it if you think everything is not fixed.
