### ISSUE TITLE
Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17)

### ISSUE THREAD

**Issue by cmagina** [docker/machine#1151]
I just installed docker-machine via homebrew and via the OSX instructions found at 'https://docs.docker.com/machine/' which gives me docker-machine version 0.2.0. After creating the docker vm via 'docker-machine create --driver vmwarefusion osxdock --vmwarefusion-memory-size 2048' I can see the vm has been started via the VMWare Fusion 7 GUI. I can ssh into it via 'docker-machine ssh osxdock'. However, when I attempt to create a docker container via 'docker create ubuntu' it fails with the client/server version mismatch error.

**Comment by hairyhenderson** [comment]
This means your Docker client is version 1.6.0, and your Docker Engine (inside the boot2docker ISO installed in VMWare Fusion) is version 1.5.0. These are unfortunately incompatible.

When 0.2.0 was released, the VMWare Fusion driver had a default boot2docker ISO URL pointing to a version with Docker 1.5.0 engine. Since then (i.e. in the upcoming 0.3.0), it's been changed to 1.6.0.

This is different (unfortunately) from how things work with the VirtualBox driver - there, the latest boot2docker ISO is grabbed.

In your case, there are two options:
1. you could try out [the latest `docker-machine` build](https://docker-machine-builds.evanhazlett.com/latest/)
2. you could point to the 1.6.0 iso explicitly by setting a flag: `--vmwarefusion-boot2docker-url https://github.com/cloudnativeapps/boot2docker/releases/download/v1.6.0-vmw/boot2docker-1.6.0-vmw.iso`

Hope that helps!

**Comment by cmagina** [comment]
Thanks for the new tools, but I am running into a new problem when trying to interact with the boot2docker host.

When I run the included docker binary after having successfully deployed boot2docker, I see this:

./docker version
Client version: 1.3.1-dev
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 831d09f
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.16/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

I get the same issue when using the released version of docker:

docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by hairyhenderson** [comment]
@cmagina - I'm not sure where "the included docker binary" is from, but that client is _way_ old. Stick with 1.6.0 :wink: 

Either way, your docker client is attempting to reach the engine through default means - a local socket - instead of TCP to the engine inside the b2d VM. You need to run `eval "$(docker-machine env dev)"` (where `dev` is the name you gave the VM when you created it with the `docker-machine create` command.

Once your shell is set up right (with the `docker-machine env` command), you can run `docker version` and it'll connect to the b2d engine.

Hope that helps!

**Comment by cmagina** [comment]
That docker came from the tarball you linked me too in your previous comment. The docker-machine contained in that tarball doesn't have an 'env' argument and I can't seem to find a means of getting it to output the environment variables. Thanks for helping me with this.

**Comment by hairyhenderson** [comment]
@cmagina - I'm confused... which tarball? The first was a link to a directory full of binaries. The one you want is https://docker-machine-builds.evanhazlett.com/latest/docker-machine_darwin_amd64. Download this, rename it to `docker-machine`, and make it executable (`chmod a+x docker-machine`).

Then you should be able to do this:
```
$ ./docker-machine env osxdock
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://172.16.62.130:2376"
export DOCKER_CERT_PATH="/Users/cmagina/.docker/machine/machines/osxdock"
# Run this command to configure your shell: eval "$(docker-machine env osxdock)"
$ eval "$(./docker-machine env osxdock)"
$ docker version
``` 

As for the `docker` binary, just use the 1.6.0 version that you already have.

**Comment by cmagina** [comment]
Hmmm....I have no idea where that tarball came from then, but you are correct. Thanks again. Everything is working now.

**Comment by hairyhenderson** [comment]
Glad to hear it! :)

**Comment by ehazlett** [comment]
Thanks for reporting!
