### ISSUE TITLE
VirtualBox: cannot kill machine when it hangs

### ISSUE THREAD

**Issue by ehazlett** [docker/machine#1219]
If the VM goes into an un-reachable state (i.e. unable to `ssh`) then machine just hangs on any command including `kill`.  We should remove anything preventing the `kill` operation so users can recover (i.e. calls to `GetState` etc).

Thx to @rrarunan for reporting!

**Comment by UserTaken** [comment]
I used a fork bomb to simulate non reponsiveness. From what I'm seeing, `executing: /usr/bin/VBoxManage showvminfo test-machine --machinereadable` is being continuously looped instead of running `controlvm test-machine acpipowerbutton` next which wouldn't have worked anyway. `Kill` should default to hard poweroff with `controlvm test-machine poweroff` and add force restart flag to run `controlvm test-machine reset`

**Comment by nathanleclaire** [comment]
Yes, so probably VirtualBox driver needs a "meaner" kill.

**Comment by nathanleclaire** [comment]
I'm not sure what more can be done about this one.  `Kill` in the VBox driver already calls `VBoxManage controlvm foo poweroff`.
