### ISSUE TITLE
Old functionality of `active` gone?

### ISSUE THREAD

**Issue by cglewis** [docker/machine#1238]
Sorry if there is already an issue about this, I was not able to find one.

It appears that using `active` now just shows the list of machines connected and which one is active.  It used to switch to the desired machine to set as active.  Is there a way to do this without having to do `env` and then copy pasting the `eval`?  Maybe we could add something like `docker-machine use b2d` to imply that it sets `b2d` as the active environment?

Having this kind of functionality built into `docker-machine` will really making scripting a lot easier and cleaner.

**Comment by nathanleclaire** [comment]
> It appears that using active now just shows the list of machines connected and which one is active

Currently in master, `docker-machine active` should just show you the name of the active machine, and error out if any arguments are given.

> It used to switch to the desired machine to set as active.

It appeared to do this, but did not actually.  Way back when machine was actually `docker hosts` and we could interface directly with what Docker was doing, that's the way it used to be, since we could actually hijack the `-H` option to Docker for our own nefarious purposes.  Now, Machine is a separate binary, and it's a consequence of the increased modularity that you have to use `env` or `config`.  

This _might_ change in the future if we can be persuaded of a way to do so which is feasible from a design and technical perspective, but there is no easy way to do it currently.

> Maybe we could add something like docker-machine use b2d to imply that it sets b2d as the active environment?

This is not possible without upstream changes to Docker, unfortunately.  However, I am a big fan of the following shell alias: 

```bash
dkr () {
    if [[ "$1" == "which" ]]; then
        docker-machine active
        return
    fi
    if [[ "$1" == "use" ]]; then
        eval "$(docker-machine env ${*:2})"
        return
    fi
}
```

If you throw that in your `~/.bashrc` / `~/.zshrc`, you can use a similar workflow:

```
$ docker-machine create -d virtualbox b2d
$ dkr use b2d
$ dkr which
b2d
```

**Comment by cglewis** [comment]
gotcha, that makes sense. thanks @nathanleclaire !

**Comment by nathanleclaire** [comment]
:+1:

**Comment by nathanleclaire** [comment]
@ehazlett @cglewis Can we close this issue?

**Comment by cglewis** [comment]
fine by me.
