### ISSUE TITLE
Need a mechanism to update boot2docker.iso image

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1285]
`boot2docker.iso` image is cached in `.docker/machine/caches`. If a newer image is available then either it should be updated automatically, or there should be an option to update the image.

**Comment by nathanleclaire** [comment]
It will be overwritten if you upgrade a particular machine, I do agree that a `docker-machine upgrade --cache` or equivalent which would work without relying on a particular machine would be quite useful.

**Comment by amylindburg** [comment]
When I installed machine, I found that the `boot2docker.iso` image cached in `.docker/machine/caches` was _not_ updated, i.e., when I installed Machine 0.2.0 (which was released with Docker 1.6), created a new machine and SSH'd in, I found that Docker 1.5 was running on my machine "rc" -- because the cache had not been updated. 

Also -- when I ran `"$ eval "$(docker-machine env rc)"` I realized that my docker client was newer than the daemon -- `Error response from daemon: client and server don't have same version (client : 1.19, server: 1.17)`; it took me a while to figure out why I was getting this error -- that the culprit was 1) the cache supplying an old version, and 2) that I had not specified the  `boot2docker.iso` when I created the machine (did not realize that I had to do this).

It would be nice not to have to explicitly upgrade the cache -- to have the cache be automatically upgraded to the latest release version of 'boot2docker.iso` when a new machine is created (or at least when a new version of machine is installed).

This won't help when we are dealing with the installation of Release Candidates -- but it will help in the general case.

**Comment by ehazlett** [comment]
I'm actually against this.  I don't think an action like a Docker version upgrade should be automatic.  Take for instance a developer that is developing against a production Docker stack at 1.6 only to find a new machine was created and automatically upgraded to 1.7.  I don't think these should be automatic.  This is exactly what the `upgrade` command is for -- to control the process.

**Comment by amylindburg** [comment]
That makes sense. I think that for newer users, then, more documentation around the cache would be helpful -- that it gets explicitly upgraded (on purpose) by the `upgrade` command so that you can maintain control over your environment. I did read the docs around `upgrade` but I guess that it was too subtle a point for me.

**Comment by nathanleclaire** [comment]
> That makes sense. I think that for newer users, then, more documentation around the cache would be helpful -- that it gets explicitly upgraded (on purpose) by the upgrade command so that you can maintain control over your environment. I did read the docs around upgrade but I guess that it was too subtle a point for me.

Yeah, I agree with @ehazlett and with this point -- in general, the "image cache" seems to fly under the radar a bit and could certainly be explained better.

That said, I still think a command to deliberately upgrade the cached ISO would be useful / something we should add.

**Comment by ehazlett** [comment]
This is the `upgrade` command right?

https://gist.github.com/ehazlett/8a8bec3817d083abf129

**Comment by nathanleclaire** [comment]
> This is the upgrade command right?

Right, but today it's always done in the context of a machine.  If you want to upgrade just the ISO, I don't think that's possible today.

**Comment by arun-gupta** [comment]
There should be support for multiple boot2docker ISO images. I may not want to update my existing docker machines to upgrade, but still want to create newer images with the most recent ISO.

**Comment by nathanleclaire** [comment]
> There should be support for multiple boot2docker ISO images. I may not want to update my existing docker machines to upgrade, but still want to create newer images with the most recent ISO.

@arun-gupta That's how it works today (unless there's a bug we've missed): Each machine has its own ISO, and only gets upgraded if you deliberately run `docker-machine upgrade name` on it.

**Comment by arun-gupta** [comment]
@nathanleclaire For two machines, there is only one `boot2docker.iso` in `.docker/machine/cache`. What does it mean by "Each machine has its own ISO"?

**Comment by nathanleclaire** [comment]
@arun-gupta Check out the machine's directory, e.g. `~/.docker/machine/machines/dev` - each machine has its own copy of the ISO and the "cached" copy is used for new machines or upgrades.

**Comment by arun-gupta** [comment]
@nathanleclaire got it! I think, then it makes more sense to just upgrade the boot2docker.iso image only :)

**Comment by jimmycuadra** [comment]
Should the cached ISO have the version number in its filename? I just spent a while trying to figure out why I couldn't create a VMware Fusion machine, and eventually discovered that it was using an old version of boot2docker that was sitting in the cache from when I tried docker-machine previously (weeks or months, I forget.) I had to remove the cached file to get a newly created machine to download the latest release and use it for creating a machine. The version mismatch was not at all obvious – I only noticed it because I opened Fusion's GUI and saw boot2docker's MOTD in the shell.

**Comment by nathanleclaire** [comment]
@jimmycuadra You can use `file`: 

```console
$ file ~/.docker/machine/cache/boot2docker.iso
/Users/nathanleclaire/.docker/machine/cache/boot2docker.iso: ISO 9660 CD-ROM filesystem data 'Boot2Docker-v1.7.1             ' (bootable)
```

Not perfect, but it works :)

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2298
