### ISSUE TITLE
Shared folders should be configurable for local VM drivers

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#13]

**Comment by dreampuf** [comment]
+1

**Comment by Maxim-Filimonov** [comment]
:+1: on NFS share. We have experienceda very bad performance with shared folder even with vmware fusion. The only tricky part with we have found is that NFS sometimes doesn't bust a cache properly -> need to change file again for machine to pickup changes.

**Comment by rawkode** [comment]
rsync or nfs would be awesome :+1:

**Comment by joshfinnie** [comment]
Cannot upvote this enough... would LOVE to see this added to machine! :+1:

**Comment by Compufreak345** [comment]
+1

**Comment by rafabene** [comment]
+1

**Comment by zymplsi** [comment]
+1

**Comment by EpocSquadron** [comment]
+1 This is the only thing holding me back from rolling toolbox out as a development environment solution for our developers. I have a hacked-together setup similar to docker toolbox that utilizes nfs specifically because vboxfs gives permissions and performance issues.

**Comment by fesor** [comment]
@EpocSquadron you can try https://github.com/codekitchen/dinghy

**Comment by vipconsult** [comment]
+1

**Comment by Besedin86** [comment]
:+1:

**Comment by posita** [comment]
I just filed Parallels/docker-machine-parallels#29, but Boot2Docker itself should be able to support mounting NFS volumes, which suggests enabling NFS mounted volumes could be handled via a driver-agnostic means (see, e.g., <https://github.com/boot2docker/boot2docker/issues/581#issuecomment-74535277>). I'm imagining something like:

```sh
% docker-machine create --help
...
  --share-type "driver"     "driver" or "nfs[:<mount_options>]" where
                            <mount_options> are optional NFS options,
                            such as "mapall=501:501,nolock,sync"
...
```

`root` or `sudo` access might be needed on the host to modify `/etc/exports`. Alternately, instructions on modifying `/etc/exports` could be printed to `stdout` as part of the `create` and `start` commands (with corresponding removal instructions printed out as part of the `rm` and `stop` commands).

**Comment by posita** [comment]
From @legal90 via this https://github.com/Parallels/docker-machine-parallels/issues/29#issuecomment-164727243 regarding my above proposal:

>... [T]his is a good idea. ... NFS support should be implemented in both of Boot2Docker and Docker Machine itself, but not in a driver because it is not related to the virtualization system directly.
>
>The good example is Vagrant and how NFS support is implemented there. Following this way, Docker Machine should manage NFS exports on the host side and also it should mount NFS folders on the guest side (during the provision step).
>So, this feature is mostly host-specific (Windows doesn't support it) rather that provider-specific (it should work for VirtualBox and VMware by the same way).

**Comment by johnsudaar** [comment]
+1

**Comment by jedipunkz** [comment]
+1

**Comment by brandontamm** [comment]
+1 - I have a /Users directory larger than my storage driver so in Virtualbox it shows "Full" 

This messes everything up when I try to change the docker-machine to use github.com/adlogix/docker-machine-nfs to share large projects like a Magento project.

When I use github.com/codekitchen/dinghy I do not have this problem, because it is mounting only the volume specified in docker-compose.

@ nathanleclaire IMO, the file sharing and volumes and mounting is a HUGE blocker for docker (no pun intended) and we should have a choice of how we mount volumes and what is actually mounted. Otherwise we have to use these workarounds to develop projects with giant file structures. For instance, I can't docker-compose up a development Magento project with 30,000 files because the volumes aren't available in time and cause everything to break. So we have to try these side projects for NFS...

Then again, I am new at this but I see SO MANY issues resulting from file shares..

**Comment by SashaOv** [comment]
+1

**Comment by rawkode** [comment]
If it helps anybody, I'm using the new `--virtualbox-no-share` flag (docker-machine) and this script to rsync files:

https://github.com/rawkode/symfony-distribution/blob/master/bin/osx-sync

We should be able to do `docker-machine create -d virtualbox --share 'rsync:.:/var/www' development` - whatever the syntax ends up - surely this isn't too far away now? :)

**Comment by nathanleclaire** [comment]
> I am wondering because I use github.com/adlogix/docker-machine-nfs to share large projects like a Magento project. I have a work machine and a personal laptop - the work machine has virtually nothing in /Users and I am able to mount the NFS, but the mount always fails when I try to mount to NFS using my laptop (with large /Users directory)

Does it give you an error message specifically indicating that this is the problem?

Have you tried doing the NFS mount manually?

**Comment by stkiss** [comment]
+1

**Comment by jmreicha** [comment]
Has there been any movement on this?

It would be great to see something like --share-type with options for NFS, sshfs, samba, etc. and (maybe?) --share-path src:dest implemented.

**Comment by mrmachine** [comment]
I use VMware Fusion (not VirtualBox) which has much more performant file sharing. However, I still need to share directories other than `/Users` to the docker host (`boot2docker` created with `docker-machine`). I want to run some docker containers that have access to files on my and other drives physically attached to my iMac. Is there any other workaround? Should I be trying to configure boot2docker to mount volumes from my NAS and iMac into the docker host? Or should I be trying to configure my containers to access the NAS and iMac volumes directly?

**Comment by jakub-c** [comment]
I've been struggling to mount something else than default `\Users` directory on Mac OS X, and here's what worked for me:

- Go to Virtual Box app
- Choose the docker VM in my case it's called 'default'
- Go to Settings -> Shared Folders
- In the Folder List double click an item under 'Machine Folders' - that's the folder docker is going to use. By default it's going to be aliased as 'Users' unless you change it

So in your `docker run` you'll be able to do `-v /Users`  or whatever name you've set up.

It's important to set it up under 'Machine Folders' not under 'Transient Folders' in order to make it work.

**Comment by posita** [comment]
@jakub-c, thanks for the VBox-specific work-around, but I don't think that's the point of this issue. As far as I understand, this is a feature request to abstract (or at least expose) each underlying drivers' shared folder mounting options through the `docker-machine` command.

**Comment by agentfitz** [comment]
Just getting started with Docker (from the Vagrant world) and this has been my biggest pain point. An easy and intuitive way to sync a host directory (from OSX) all the way down to the web root in the container would be HUGE.

**Comment by fesor** [comment]
@agentfitz for OSX there is [dinghy project](https://github.com/codekitchen/dinghy)

**Comment by agentfitz** [comment]
@fesor Thanks! Hey, last night I realized I had totally missed something. Since /Users is automatically mapped from OSX to the docker-machine (if I'm not mistaken), then setting up your synced volume from your host OSX all the way down into the docker container is as simple as targeting a specific directory from within /Users for your mapping, so:

`docker run -v /Users/my/folder:/var/www me/my-docker-image`

I actually got this working last night after a hidden tip on Stackoverflow. Is this clearly laid out in the Docker docs somewhere? Also, considering how easy this is (once you know how it works), why do all these other syncing projects exist?

**Comment by mrmachine** [comment]
@agentfitz because VirtualBox is terribly slow at sharing folders from OSX into the VM. Even VMware, which is much faster, is still supposedly not as fast as NFS (which `dinghy` uses), which is again not as fast as rsync (which `docker-osx-dev` uses). Rsync has the drawback of actually copying files into the container, though, which often may not be practical. Plus, there are permissions issues. Host volumes mounted into the container will have the same UID/GID as the host. If the UID/GID of the process running inside the container doesn't match, you could have issues.

**Comment by vipconsult** [comment]
https://github.com/adlogix/docker-machine-nfs

is by far the most simple solution and my favourite.
It is just a script which sets the nfs share even after the machine is creates.

**Comment by agentfitz** [comment]
@mrmachine ah, so are you saying the -v flag to the docker run command uses VirtualBox's built in syncing under the hood? I do remember reading about performance concerns but when I set it up last night source code changes seemed to be reflected in the docker container instantly. Is it an issue with bigger files (like images or something?) as opposed to source code?

I also hadn't considered the permissions issues, so thanks for pointing those out. @vipconsult thanks for sharing, I'll check it out.

But seriously though, where are the official dockers docs on all this?

**Comment by nathanleclaire** [comment]
> ah, so are you saying the -v flag to the docker run command uses VirtualBox's built in syncing under the hood?

`-v` flag for `docker run` specifies that the first part of the arg (before the colon) should be bind mounted into the container at the second part of the arg.  It _happens_ to be the case that we mount `/Users` from the host (OSX) into `/Users` in the VM (Linux / boot2docker) at boot of the VM.

> What is the "syncing technology" it uses? I do remember reading about performance concerns but when I set it up last night source code changes seemed to be reflected in the docker container instantly. Is it an issue with bigger files (like images or something?) as opposed to source code?

VirtualBox shared folders -- they work fine for simple use cases, but with large files and/or lots of reads and writes their performance is not ideal.

**Comment by Compufreak345** [comment]
@agentfitz For me the performance issues are huge as I use SQLite-databases. I am also using the script mentioned by vipconsult since some months, it works really well.

**Comment by joergpatz** [comment]
+1 for adding more driver options for sharing folders. would be great to see this added to docker-machine.

**Comment by erdnaxeli** [comment]
+1

**Comment by raeesiqbal** [comment]
bump...

**Comment by raeesiqbal** [comment]
A [method recommended by @jas99 ](https://github.com/docker/machine/issues/1826#issuecomment-143863060) worked for me.

**Comment by kevinpapst** [comment]
+1

**Comment by MrLeit** [comment]
+1

**Comment by walterdolce** [comment]
+1 to having the ability to configure shared folders outside the default `/Users` folder. It would be great to see this currently missing functionality be prioritised so people doesn't have to resort to this: https://github.com/docker/machine/issues/1826#issuecomment-248436823.

**Comment by nathanleclaire** [comment]
> +1 to having the ability to configure shared folders outside the default /Users folder. It would be great to see this currently missing functionality be prioritised, implemented and released so people don't have to resort to this: #1826 (comment).

This _could_ mean a lot of different things, but FWIW, it'll be [possible in 0.9.0](https://github.com/docker/machine/pull/3798) thanks to @u-foka !

**Comment by walterdolce** [comment]
Nice! Thanks @nathanleclaire and @u-foka! 🚀 

Breaking down what I said above:
> having the ability to configure shared folders outside the default /Users folder

To:
> outside the default /Users folder

That means having the ability to allow docker to see the following (note there are _multiple_ folders, not just an "alternative" like the initial comment in #1826 says):

```
/Users
/Volumes
/whatever
```
Basically what Docker for Mac does:
<img width="381" alt="screen shot 2016-12-02 at 11 55 03" src="https://cloud.githubusercontent.com/assets/6195629/20833186/385e8da0-b886-11e6-8efb-5a9d9f22a218.png">

**Comment by nathanleclaire** [comment]
going to close this issue in favor of more specific ones.  "should be configurable" is overly broad.  thanks all!
