### ISSUE TITLE
SSH doesn't work with driver 'none'

### ISSUE THREAD

**Issue by aperepel** [docker/machine#1303]
`docker-machine version 0.3.0-dev (fec8b4a)`

I've created a convenience (shorter) link to the running machine
`docker-machine create --url=tcp://agrande-docker-1.cloudapp.net:2376 az1`

The SSH doesn't work if trying to go through the link, and `env` doesn't know anything about the machine:
```
06:12:31::docker-964 ♨ >  docker-machine ls
NAME               ACTIVE   DRIVER       STATE     URL                                        SWARM
agrande-docker-1   *        azure        Running   tcp://agrande-docker-1.cloudapp.net:2376
az1                *        none                   tcp://agrande-docker-1.cloudapp.net:2376
06:13:36::docker-964 ♨ >  docker-machine ssh az1
Error: Cannot run SSH command: Host "az1" is not running
06:13:44::docker-964 ♨ >  docker-machine ssh agrande-docker-1
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Jun  3 22:10:04 UTC 2015

  System load:  0.0               Processes:              229
  Usage of /:   5.0% of 28.80GB   Users logged in:        0

... (omitted)

Last login: Wed Jun  3 22:10:05 2015 from pool-108-29-17-62.nycmny.fios.verizon.net
ubuntu@agrande-docker-1:~$ exit
logout
06:14:04::docker-964 ♨ >  docker-machine env az1
open /Users/aperepelytsa/.docker/machine/machines/az1/ca.pem: no such file or directory
06:14:10::docker-964 ♨ >
```

**Comment by ehazlett** [comment]
This driver is meant for testing.

@nathanleclaire perhaps we should remove this from the docs as being a "usable" driver?  Generic replaces what it did before I believe.

**Comment by nathanleclaire** [comment]
Hmmm, yeah, `none` and `url` tend to be _really_ confusing, and we generally don't pay them much attention, so we might want to consider deprecating or clarifying their roles more like you mentioned.

**Comment by hairyhenderson** [comment]
> perhaps we should remove this from the docs as being a "usable" driver?

+1

**Comment by nathanleclaire** [comment]
Well, `--url` is a bit different because the basic idea is to have an existing daemon which is running and configured already, and you just set the port to connect on.  With our TLS setup though, I'm really starting to think it's more trouble than it's worth.

**Comment by dmp42** [comment]
I don't see `none` anymore (?) in the docs.

Closing this for bookkeeping. Let me know if there is still something to be done.

**Comment by nathanleclaire** [comment]
The original idea for "

**Comment by nathanleclaire** [comment]
No, `none` is not just for testing.

It was originally intended to be the "default" driver which you could use to just add an existing host in without doing anything, e.g. `docker-machine create --url unix:///var/run/docker.sock local`

It is not intended to make it so that SSH could work (although maybe it could?). However, it has definitely languished in terms of support for even the simplest use case and needs to be fixed.

**Comment by vecernik** [comment]
docker-1.9@ubuntu14 / docker-machine-0.5@osx is broken now, but used to work with previous versions. 
user@osx$ ping dockerhost; ssh dockerhost; telnet dockerhost 2376 - OK

user@osx$ docker-machine -D create -d none --url=tcp://dockerhost:2376 dockerhost
Docker Machine Version: 0.5.0 (HEAD)
Found binary path at /usr/local/bin/docker-machine-driver-none
Launching plugin server for driver none
Plugin server listening at address 127.0.0.1:51018
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-none
Launching plugin server for driver none
Plugin server listening at address 127.0.0.1:51026
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(dockerhost) Calling RpcServerDriver.GetMachineName
(dockerhost) Calling RpcServerDriver.DriverName
(dockerhost) Calling RpcServerDriver.GetCreateFlags
(dockerhost) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(dockerhost) Calling RpcServerDriver.PreCreateCheck
(dockerhost) Calling RpcServerDriver.GetConfigRaw
(dockerhost) Calling RpcServerDriver.GetConfigRaw
Creating machine...
(dockerhost) Calling RpcServerDriver.Create
(dockerhost) Calling RpcServerDriver.GetConfigRaw
(dockerhost) Calling RpcServerDriver.GetConfigRaw
(dockerhost) Calling RpcServerDriver.DriverName
Reticulating splines...
(dockerhost) Calling RpcServerDriver.GetConfigRaw
(dockerhost) Calling RpcServerDriver.GetConfigRaw
To see how to connect Docker to this machine, run: /usr/local/bin/docker-machine env dockerhost

user@osx: docker-machine env dockerhost
docker-machine -D env dockerhost
Docker Machine Version: 0.5.0 (HEAD)
Found binary path at /usr/local/bin/docker-machine-driver-none
Launching plugin server for driver none
Plugin server listening at address 127.0.0.1:51054
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(dockerhost) Calling RpcServerDriver.GetState
Error running connection boilerplate: dockerhost is not running. Please start it in order to use the connection settings

Any ideas why "none" driver has stopped working?

**Comment by Oliboy50** [comment]
I think it has been replaced by `generic` driver 
https://docs.docker.com/machine/drivers/generic/
