### ISSUE TITLE
VMware Fusion Docker Performance Issue after Modifying Portwarding Config

### ISSUE THREAD

**Issue by chouclee** [docker/machine#1353]
See description: https://github.com/boot2docker/boot2docker/pull/925#issuecomment-111320383
boot2docker iso: https://github.com/boot2docker/boot2docker/pull/925
Finally I figured out how to reproduce this problem. @nathanleclaire 

1. Run a docker machine first. 

2. Change the NAT port forwarding config file nat.conf under /Library/Preferences/VMware\ Fusion/vmnet8
![screen shot 2015-06-12 at 10 18 20 am](https://cloud.githubusercontent.com/assets/3389485/8135476/698bec3a-10ec-11e5-8e6e-831fef299e02.png) 
(uncomment the line "8080 = 172.16.2.135:8080")

3. follow the official instructions: http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1026510, restart NAT services
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --stop
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start

4. Run a docker containing Tomcat with flags
-v /Users/zhoucli/Desktop/webapps:/opt/tomcat/webapps -v /Users/zhoucli/Desktop/logs:/opt/tomcat/logs. Launch the app.  Now the deployment time would increase from around 24s to about 160s.
![screen shot 2015-06-12 at 11 10 38 am](https://cloud.githubusercontent.com/assets/3389485/8136835/da24ad9a-10f3-11e5-82b9-4b1b9489f207.png)

5. Comment the port forward config. Restore the original file. 
Repeat procedure 4. Run a new docker, the performance issue remains.

6. Shut Down the VMware App, make sure the config file is the same as before, restart the docker machine. The issue remains.

7. Restart computer, start docker machine, docker, and launch app. The issue remains.
!!!! Now, open VMware GUI, there would jump out a window
![screen shot 2015-06-12 at 10 28 45 am](https://cloud.githubusercontent.com/assets/3389485/8135673/e2e6ded6-10ed-11e5-8b48-f5478155e689.png)

8. Delete the machine, create a new machine could solve the performance problem, which means I couldn't use port forwarding...
![screen shot 2015-06-12 at 11 09 45 am](https://cloud.githubusercontent.com/assets/3389485/8136846/e496621e-10f3-11e5-94e5-df738858c99b.png)

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
The shared folder feature does not involve the network at all, it uses a specific host/guest channel to perform file transfers through the hypervisor.

The warnings you see on the console are expected, as boot2docker does not include the `vmstat` command.

The docker-machine driver for Fusion only mount `/Users` on the OSX system as a shared folder under  `/Users` in boot2docker, to test shared folder performance, instead of deploying a tomcat container, log into boot2docker and perform a `time cp` of a large file to/from the shared folder mount.

**Comment by chouclee** [comment]
@frapposelli  Yes, you are right. I used the command time cp suggested by you. The net config didn't affect the shared folder performance at all. 

I guess the Docker's performance was affected. "docker run" command would take more than 20s to load the private image after modifying the config. Previously it was blazingly fast. You are an expert on VMware, do you have any suggestions on how to find out the reasons?

**Comment by frapposelli** [comment]
@chouclee I'm not very well versed on the networking stack of Fusion but there's nothing there that could justify a 20 seconds delay, I suggest you to run some tests to better isolate the root cause, like running an [`iperf`](https://iperf.fr/) test between host and guest and see if it changes when you're using the port forwarding feature.

**Comment by chouclee** [comment]
@frapposelli thanks for the suggestion. 
issue closed. I do need more tests to find out what's really going on.
