### ISSUE TITLE
Feature Request: Add support for Github Token to avoid Github API Rate limits

### ISSUE THREAD

**Issue by mtscout6** [docker/machine#1483]
I tried creating a machine today for the first time and I got the following output:

```
➜  ~  docker-machine create --driver virtualbox dev
Creating CA: /Users/smithm/.docker/machine/certs/ca.pem
Creating client certificate: /Users/smithm/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/smithm/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Error creating machine: Error demarshaling the Github API response: json: cannot unmarshal object into Go value of type []struct { TagName string "json:\"tag_name\"" }
You may be getting rate limited by Github.
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

I'm presuming the offending code is here: https://github.com/docker/machine/blob/master/utils/b2d.go#L71-L95

I'm pretty sure I ran into this because I used `brew search docker-machine` which dinged my rate limit. Homebrew allowed an option for me to add an environment variable to define a token, which is what allow me to install docker-machine on my laptop. Which may be related to unseen issues introduced by #130 which discussed the addition of the homebrew formula for docker-machine.

Github does allow you to authenticate with an auth token which significantly increases the rate limit you can use. Has there been any consideration to adding configuration support to define such a token? Perhaps through an environment variable?

Without such support I have to wait up to 30 minutes to run this command. Not the end of the world, but slightly frustrating.

**Comment by nathanleclaire** [comment]
Yeah, I agree it's bad.  I think we want to move to having a file on master in boot2docker/boot2docker which we update per-release to check instead of using the API.

**Comment by skatsuta** [comment]
+1

**Comment by nathanleclaire** [comment]
@tianon What do you think about adding a file to [docker/boot2docker](https://github.com/docker/boot2docker) which contains only the current version as contents?  My thinking is we could update release automation in that repo to modify that automatically. It would simplify the relevant Machine code (no more unmarshalling JSON etc.) and solve the API response limit issue.

**Comment by tianon** [comment]
Hmm, I'd actually probably be more in favor of something that tracks the releases API more closely, because eventually it'd be cool to have a flag to re-enable pre-releases directly so people could test RCs even more trivially.

Basically taking that JSON file (or perhaps a simpler version of it) and tracking that directly, is my thought.  Then we'd only hit the API once a day to keep that file updated (on a simple cron job).

Are the direct "raw" URLs not subject to the same API rate limits?

**Comment by nathanleclaire** [comment]
> Are the direct "raw" URLs not subject to the same API rate limits?

I'm not 100% sure, but a command like `ab -n 1000 -c 100 https://api.github.com/repos/docker/machine/releases` gives me 900 failed requests, whereas `ab -n 1000 -c 100 https://raw.githubusercontent.com/docker/docker/master/experimental/compose_swarm_networking.md` gives me 0 failed requests.  I assume because one is just a static file whereas the other has to actually hit API servers / Ruby etc.?  Admittedly unscientific.

**Comment by grepory** [comment]
Is there a workaround for this issue? Is my only recourse to destroy my docker machine and rebuild with  the appropriate argument to --vmwarefusion-boot2docker-url (or the equivalent for each driver I use)?
