### ISSUE TITLE
Volumes not mounting on amazonec2 driver

### ISSUE THREAD

**Issue by saada** [docker/machine#1566]
For some reason, my volumes don't get mounted when setting up a machine on amazonec2 like shown below
```shell
docker-machine create -d amazonec2 mymachine
eval $(docker-machine env mymachine)
docker-compose up
```

My docker-compose.yml has a volume setup like this
```yaml
volumes:
    - ..:/app
```

Everything succeeds but my volumes aren't there when I `docker-machine ssh mymachine` or when I try accessing my web app.
Is there a workaround for this? Is it a docker/compose specific issue? Or the ec2 driver itself?

I tried to use
```shell
docker-machine scp -r . mymachine:/home/ubuntu
docker-compose up
```

But still no luck.
Thank you!

UPDATE:
I couldn't find my files using this command either. I think it's the ec2 driver itself that's not mounting my local files?
```
docker run -it -v `pwd`:/app busybox sh
```

**Comment by nathanleclaire** [comment]
Hi @saada 

This is expected behavior for cloud drivers such as `amazonec2` where we are not doing any folder sharing for you with the created instance.  It happens to be the case that we mount `/Users` into the VMs we create locally using shared folders, but nothing of this sort happens with cloud providers.

When you do a `docker run` with the `-v` flag, you are specifying to the Docker daemon on that host to use the _local_ (to the daemon) directory from the first part of the argument (before the colon).  Because that directory doesn't exist on the server, only on your local laptop, it will be created by the Docker daemon as an empty directory and its contents will be empty in the container.  If you want to copy the files using `docker-machine scp`, they will show up on the remote host, but you have to edit your compose file or `docker run` command to have the correct directory.  That `..` in the Compose file will turn into a local path, e.g. `/Users/saaba/webapp` but the location you copied them to was `/home/ubuntu`.
