### ISSUE TITLE
[BUG] Inspect machine expected to return all machine details. 

### ISSUE THREAD

**Issue by FrenchBen** [docker/machine#1582]
Although pretty basic, your typical `docker-machine ls` returns the following:
* Name
* Active (default)
* Driver
* State
* Url
* Swam

Yet `docker-machine inspect <machine-name>` doesn't show:
* Active (default)
* State
* Url

Is there a reason for those not to be included?

**Comment by nathanleclaire** [comment]
The reason is that `inspect` just returns what's marshalled to disk for the Machine config.  It was never meant to be a "consistent" way to access things like IP which could change between invocations.  I am considering re-working inspect and the way things are stored on disk to make them more flexible and include things like this, but it will take time.

**Comment by FrenchBen** [comment]
Thanks for the feedback on this @nathanleclaire  - :+1: on adding some flexibility to what's stored on disk.
I'll close this for now, unless you want to keep it open as a #feature ?

**Comment by nathanleclaire** [comment]
Nah, closing is OK.
