### ISSUE TITLE
VMWare Fusion driver does not create .vmdk so VM never starts

### ISSUE THREAD

**Issue by dch** [docker/machine#1644]
```
docker-machine create -d vmwarefusion \
>   --vmwarefusion-memory-size 4096 \
>   --vmwarefusion-boot2docker-url $B2DURL \
>   --vmwarefusion-cpu-count 2 \
>   my
Downloading boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.7.1/boot2docker.iso...

Creating SSH key...
Creating VM...
Starting my...
Waiting for VM to come online...
Error creating machine: Machine didn't return an IP after 120 seconds, aborting
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

Looking in `~/.docker/machine/machines/my/
```
-rw-------+ 1 dch  staff    27M  4 Aug 14:22 boot2docker.iso
-rw-------+ 1 dch  staff   1.6K  4 Aug 14:22 config.json
-rw-------+ 1 dch  staff   1.6K  4 Aug 14:22 id_rsa
-rw-------+ 1 dch  staff   381B  4 Aug 14:22 id_rsa.pub
-rw-r--r--+ 1 dch  staff   1.7K  4 Aug 14:22 my.vmx
```

env:

```
docker-compose version: 1.4.0rc3
Docker version 1.7.1, build 786b29d
docker-machine version 0.3.1 (HEAD) actually v0.4.0-rc1
7646859924bcff395e3765b327bb579fad1a47f10bda80c5dfa0eca370e01010  boot2docker.iso
```

NB docker-machine is actually `v0.4.0-rc1` aka `97783b538b7780a306c34bc70d0e22eaa4418caf2d6ec5f11b920a357e9759a5` but the versioning inside the rc is incorrect.

**Comment by brendanjerwin** [comment]
I seemed to have the same issue. 
Ran with the `--debug` flag and saw that it was trying to run vmware from `/Applications` but I had installed it with `brew cask` and it wasn't there.
Uninstalled with cask, reinstalled the normal, barbaric, way, and tried again.

Works just fine.

So, I'd say the problem is one (or both) of these:

  * machine should error if it tries to execute a nonexistent binary.
  * machine should ask OS X where the vmware bundle is, and run the binary from there. (might get weird if there are multiple .app bundles on the machine.)

**Comment by ehazlett** [comment]
I'm not sure where you got the binary from.  Would you mind trying the latest rc2 available (https://github.com/docker/machine/releases/tag/v0.4.0-rc2)?

**Comment by brendanjerwin** [comment]
@ehazlett was that for me? It works fine for me now, the issue seems to be centered around how/where _vmware fusion_ is installed.

**Comment by ehazlett** [comment]
@brendanjerwin sorry the OP.  Ok thanks!

**Comment by dch** [comment]
@ehazlett v0.4.0-rc2 works perfectly. thank you *so* much!
