### ISSUE TITLE
Switch to local Docker Host after docker-machine env

### ISSUE THREAD

**Issue by AlexZeitler** [docker/machine#1659]
I can switch to the machine dev using

eval "$(docker-machine env dev)"

Docker commands now are issued against dev

How can I switch back to my local Docker host?

**Comment by mattjmcnaughton** [comment]
Since the command you issued sets `DOCKER_HOST` to the the ip of the `dev` machine, my guess is setting the `DOCKET_HOST` environment variable to `''` with `export DOCKER_HOST=''` would switch you back to your local host. But idk if there is a docker-machine command for doing this.

Hope that helps!

**Comment by UserTaken** [comment]
`eval "$(docker-machine env -u)`

**Comment by AlexZeitler** [comment]
@mattjmcnaughton @UserTaken Thanks!

**Comment by harishanchu** [comment]
Got following error when I try the command `eval "$(docker-machine env -u)"`

```
Error trying to get host "": Loading host from store failed: open /home/ec2-user/.docker/machine/machines/config.json: no such file or directory
sudo: eval: command not found
```
