### ISSUE TITLE
create hangs forever on OSX

### ISSUE THREAD

**Issue by kopiczko** [docker/machine#1801]
Hey,

OSX: 10.10.5

```
~/org ❯❯❯ docker-machine --version
docker-machine version 0.4.1 (e2c88d6)

~/org ❯❯❯ VBoxManage --version
5.0.0r101573
```

I was trying to upgrade from boot2docker to docker-machine. I had removed boot2docker and docker (installed with brew), and removed ~/.docker directory.
When I try to create new default machine:

```
~/org ❯❯❯ docker-machine create  --driver virtualbox default
Creating CA: /Users/pawel/.docker/machine/certs/ca.pem
Creating client certificate: /Users/pawel/.docker/machine/certs/cert.pem
Image cache does not exist, creating it at /Users/pawel/.docker/machine/cache...
No default boot2docker iso found locally, downloading the latest release...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.1/boot2docker.iso to /Users/pawel/.docker/machine/cache/boot2docker.iso...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
```

`docker-machine ls` output (asks me for password):

```
~/org ❯❯❯ docker-machine ls
Password:
Password:NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Timeout
```

I also see 'Password:' prompt in Docker Quickstart Terminal:

<img width="682" alt="screen shot 2015-09-03 at 19 50 27" src="https://cloud.githubusercontent.com/assets/4608994/9666241/346e329a-5275-11e5-9be3-1f4510bf97e2.png">

**Comment by rayward** [comment]
+1 same issues exactly.

**Comment by ehazlett** [comment]
Hmm @nathanleclaire do you see the same behavior with 1.8.1?  It looks like the SSH keys are not setup properly.

**Comment by nathanleclaire** [comment]
I haven't been seeing issues like this myself, but it's been a while since I've booted up the Quickstart terminal.  I'll give it a whirl soon.

**Comment by xi2008wang** [comment]
is virtualbox 5.0.0 bug!
upgrade virtualbox 5.0.4 !
http://download.virtualbox.org/virtualbox/5.0.4/VirtualBox-5.0.4-102546-OSX.dmg

**Comment by webframp** [comment]
How can I confirm if it's a vbox bug?
I'm seeing the same thing with the latest VirtualBox:
```
~ ❯❯❯ VBoxManage --version
5.0.4r102546
~ ❯❯❯ docker-machine --version
docker-machine version 0.4.1 (HEAD)
~ ❯❯❯ docker --version
Docker version 1.8.2, build 0a8c2e3
```

**Comment by alrayyes** [comment]
+1

```shell
➜  ~  docker-machine ls

NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Timeout
```

**Comment by nathanleclaire** [comment]
@alrayyes can you please Gist the output of running `docker-machine --debug ls`?

**Comment by alrayyes** [comment]
[Here](https://gist.github.com/alrayyes/79bfc9bfc51d44c505cf) you go.

**Comment by buddhafinger** [comment]
I was experiencing similar issues:

My setup:
- OS X 10.10.5
- VirtualBox 5.0.4
- Docker Toolbox 1.8.2c

Problems experienced:
- Quickstart terminal launches default instance and then prompts for password.
- Same D-Bus not installed errors in the log.
- Unable to successfully recreate the instance using Kitematic (failed as unable to connect to instance)

Resolution: 
- Deleted the default docker machine and all associated files.
- Deleted  'Host only Networks'  in Virtualbox - Preferences - Network - Host Only Network.
- Launch Kitematic and let it create the default VM (successfully)
- Launch Docker QuickStart terminal and it now works without any problems.

I can now launch docker instances via docker quick start term and use kitematic without any issues.

I got the solution from the link below, I assume it was caused by a conflict with an existing host only network.

https://github.com/docker/machine/issues/1699

**Comment by alrayyes** [comment]
adding 127.0.0.1 localhost to /etc/hosts seems to fix the problem for me.

**Comment by nathanleclaire** [comment]
This issue is very long and contains a lot of digressions.  Please retry the faulty commands with Machine 0.5.0.  If someone continues to encounter similar ones please open a new one at https://github.com/docker/machine/issues/new with detailed information including:

- Which OS you are on
- Anything atypical in networking configuration (VPN, proxy, SSH configuration settings, etc.),
- Output of the misbehaving commands with the `--debug` flag
- the VirtualBox logs from `~/.docker/machine/machines/name/name`.  

Thanks!

- N

**Comment by kopiczko** [comment]
0.5.0 works for me. Thanks!

**Comment by TimoSolo** [comment]
Did the `docker-machine rm default` thing a couple times, but takes ages to download image.

Found a simpler solution though! Open VirtualBox, turn off the "default" machine. Run Docker Quickstart and it starts up the VM and connects fine!

**Comment by kootenpv** [comment]
I really hate how machine screws this up everytime. The Quickstart doesn't fix a thing. I've literally done everything all the threads related to this bug suggest. Guys, please give me access to Docker Beta, I cannot stand this.
