### ISSUE TITLE
docker-machine creates new VirtualBox Host-Only Network adapter on restart on Windows 8.1 x64

### ISSUE THREAD

**Issue by bofm** [docker/machine#1804]
Whenever I restart docker machine like this:
```
 docker-machine stop default
 docker-machine start default
```
I get a new `VirtualBox Host-Only Network #N` adapter created in my OS.
One day I realized that I have 8 network adapters:
```
VirtualBox Host-Only Network
VirtualBox Host-Only Network #2
...
VirtualBox Host-Only Network #8
```

```
Windows 8.1 x64
VirtualBox 5.0.2r102096
DockerToolbox-1.8.1c
docker-machine.exe version 0.4.0 (9d0dc7a)
Docker version 1.8.1, build d12ea79
```

**Comment by Kewai** [comment]
Same problem here with windows 10

**Comment by rwilliams** [comment]
Possibly related to #1843

**Comment by rwilliams** [comment]
I'm pretty sure that this is virtualbox issue which is 'fixed' in 5.0.4. Unfortunately then you run into #1843. 

So far what i've seen using Docker Toolbox on windows is that it's almost a must to blow away your vm's and network adapters in virtualbox to isolate bugs that are in the latest software and not be bogged down by old bugs, or in some cases have things work when they shouldn't if you start from scratch.

**Comment by David-Crty** [comment]
Same problem here, i'm forced to restart my pc to get back the connection.

**Comment by michalborek** [comment]
Same for me. The workaround (instead of restarting OS) is removing network adapters in virtualbox and restart docker-machine. I hope the fix will be soon released, since it is really annoying.

**Comment by dgageot** [comment]
Closing since it should be better now. #2091 should improve it even more.

**Comment by 2uanta** [comment]
I still have the problem with 1.9.0. As far as I can see, this problem has never been fixed.
So far I see that the problem happens every time Windows is rebooted, Docker Quickstart Terminal would create a new VirtualBox host-only adapter and any docker command would fail to contact the VM, even if the VM is started. My workaround is to stop the VM with 'docker-machine stop default', go into VirtualBox Preferences and delete all the Host-only adapters and restart the Docker QuickStart Terminal.

Here is my environment:

Windows 8.1
$ docker info
Containers: 0
Images: 13
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 6Z7T:LA6P:KHL5:Y3R5:WVG7:Z5YC:CMGT:KJBY:32NZ:YO3A:SR3E:KJXL
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 18
 System Time: 2015-11-13T16:58:19.177374758Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

The problem started when boot2docker is replaced by docker-machine or docker-tools.

I used to work a lot on Docker but this bug prevented me to do any serious work since.

**Comment by hiteshjoshi1** [comment]
Same here, I am facing the same problem. It is not annoying. It is a show stopper.
I wonder , how would i ever use Docker for any serious work if i lose interner connectivity everytime I start/stop a VM.

**Comment by kenburcham** [comment]
This is still a problem on Windows Server 2012 R2 Standard with Virtual Box 6.0.8. 

After much pain and suffering I've finally realized I have to follow 2uanta's advice EVERY time the server reboots for windows updates (mandatory from our IT dept). 

Here are my steps:
1) Stop the VM via virtual box manager.
2) Open network control panel and disable ALL host only adapters except the last one.
3) Run Quickstart terminal. It will create a NEW host-only adapter. I'm up to #17 now. 
4) in network control panel, disable what was the last host-only adapter since it will have the same IP address as the newly created one.
5) use quickstart to do what you need to do.

Once the machine reboots you have to do this again.
