### ISSUE TITLE
Shared folders on VirtualBox driver does not work

### ISSUE THREAD

**Issue by onbjerg** [docker/machine#1814]
I am using Windows 10 with the latest testbuild of VirtualBox. I can spin up a machine and everything works, except that I can't share new folders with the machine.

My projects all reside on a different drive (D:), and one of the following things always happen:

1. The machine creates the folders, but it doesn't sync either way
2. Nothing happens. No folders are created or anything.

This is how I add shared folders:

1. Turn off the machine with ``docker-machine stop dev``
2. Add the shared folder through VirtualBox GUI. I make sure it automounts and is permanent.
3. Start up the machine again.

**Versions**
VirtualBox: 5.0.3 r102467
Docker Toolbox: 1.8.1c
Windows 10 Pro

**Comment by ehazlett** [comment]
By default, Machine will only share your home directory.  If you want to add more, you need to add them using the VirtualBox UI.

**Comment by onbjerg** [comment]
@ehazlett If you read my issue, I did exactly that. It did not work.

**Comment by nathanleclaire** [comment]
@onbjerg The shares are probably not mounted when the VM boots.  There is an additional step to run a command like `sudo mount -t vboxsf sharename /path` when the VM boots.  I wouldn't count on auto-mounting- historically there have been some complications with boot2docker (the OS) which prevent it from working.

**Comment by onbjerg** [comment]
Okay, that worked. Thanks @nathanleclaire!

**Comment by nathanleclaire** [comment]
You're welcome!

**Comment by juharris** [comment]
Those still having trouble may find [this post][http://serverfault.com/a/674978/319713] helpful. It details how to add the shared folder, create the directory in the VM (using `mkdir`), then how to mount it.

**Comment by ginolon** [comment]
There is a way to do this without using VirtualBoxUI, just the code in shell?

**Comment by nathanleclaire** [comment]
@ginolon Yes there is but you have to call out to the location of where `VBoxManage` is directly, as well as know the actual commands to create the shared folders.

**Comment by jepma** [comment]
@ginolon you can do this like this `VBoxManage sharedfolder add default --name "workspace" --hostpath /Volumes/Data/workspace/` where default is the name of your virtual-machine and /Volumes/Data/workspace the directory on your host machine.

**Comment by yelmu** [comment]
You don't need to run the additional step  `sudo mount -t vboxsf sharename /path` if you use Users or /Users as a share/folder name in VirtualBox.

Check [boot2docker readme](https://github.com/boot2docker/boot2docker/blob/master/README.md), it tries to automatically mount some predefined VBox share names. /c/Users is automatically mapped to C:\Users but /Users can still be mapped to D:\Code in VBox GUI.

Run `docker run -v /Users:/code` and now /code in Docker container maps to D:\Code.

**Comment by alainkr** [comment]
Is it possible to script "sudo mount -t vboxsf ..." somewhere inside the boot2docker ? So that it is executed each time the docker-machine starts ?

**Comment by nathanleclaire** [comment]
@alainkr Check out https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition

**Comment by nikolakanacki** [comment]
Since this is one of the top search result hits, I'll just post what worked for me.

`Host: Mac OSX 10.11`
`Docker: 1.10.3`
`VirtualBox: 5.0.16 r105871`

1. From VirtualBox UI (or cmd) share the folder you want available in the host, have it automount. For this example, let's say the path is: `/Volumes/DATA/dev` and you named it: `dev`.
2. Open your virtualbox console (from VBUI or ssh) and create `/var/lib/boot2docker/bootlocal.sh` file:
`$ touch /var/lib/boot2docker/bootlocal.sh`
3. Add the following content using `vi` (or whatever is available, nano isn't):
```
#!/bin/sh

# Make directory path to the folder you shared with VirtualBox UI.
# We'll make the exact structure you find on your host so it's
# easier to target with docker from the host:
mkdir -p /Volumes/DATA/dev

# Mount it using "mount -t vboxsf <name> <path>":
mount -t vboxsf dev /Volumes/DATA/dev
```

(quick `vi` ref: open file > `vi <filepath>`, enter insert mode > `i`, save and quit > `:wq`)

And that's it!

We create `/var/lib/boot2docker/bootlocal.sh` because it is executed during boot (you can put loads of stuff in there to prepare your machine). Also, nothing outside `/var/lib/boot2docker` directory will be preserved once you stop the machine. Repeat for every directory you want shared.

Hope it helped.

**Comment by janhartigan** [comment]
Anyone coming to this using Docker Toolbox on Windows can avoid running the mount lines manually by modifying `C:\Program Files\Docker Toolbox\start.sh` to include this:

```bash
STEP="Mounting web directory"
"${DOCKER_MACHINE}" ssh default 'sudo mkdir --parents //c/Web'
"${DOCKER_MACHINE}" ssh default 'sudo mount -t vboxsf c/Web //c/Web'
```

This can go after the step `Checking status on $VM` and before `Setting env`.

**Comment by cpprookie** [comment]
@juharris   thanks a lot, It works as it should be

**Comment by abarcenas29** [comment]
@juharris I get an error when I tried your fix.

`Looks like something went wrong in step ´Mounting web directory´... Press any key to continue...`

My change
```
STEP="Mounting web directory"
"${DOCKER_MACHINE}" ssh default 'sudo mkdir --parents //c/www/docker'
"${DOCKER_MACHINE}" ssh default 'sudo mount -t vboxsf c/www/docker //c/www/docker'
```
My docker containers are located in `C:\www\docker`

**Comment by juharris** [comment]
@abarcenas29 wow people are still using Docker Toolbox? If you have Windows 10, then there's better more native like support now: https://store.docker.com/editions/community/docker-ce-desktop-windows

As for your error, I'm really not sure sorry and I haven't used Docker Toolbox in months. Maybe you C drive is already mounted? Which line gave the error?

**Comment by janhartigan** [comment]
@juharris the underlying problem is that most people don't want to (or have the means to) upgrade to Windows 10 Pro. You can't use Docker for Windows with the standard edition of Windows 10. I personally have Pro on all of my machines, but I feel like Microsoft should make Hyper-V a base feature so they don't lose a bunch of devs to other operating systems. Docker for Windows is a million times more usable than Docker Toolbox, and that alone makes the extra $100 worth it for me, but not everyone is going to have the same economics.

**Comment by jeremyVignelles** [comment]
@juharris Yeah, people are still using Docker Toolbox, and I'm one of those: Hyper-V is for me a huge source of frustration, it doesn't allow me to use Virtualbox at the same time because it takes ownership of the virtualization chip. All my virtual machines are on Virtualbox, which I find way more convenient to use for linux VMs, so I don't want to switch. Switching between Hyper-V and Virtual box requires rebooting and reinstalling Hyper-V each time, so, sadly, I won't upgrade to the new Docker

**Comment by jeremyVignelles** [comment]
I just found another option to share a folder to the virtualbox VM: You can create your VM with the following command line:

```
docker-machine create --driver virtualbox --virtualbox-share-folder "c:\project:/c/project" default
```

For that to work, you will need to remove and recreate your VM, you will need to add the same option if you want to keep the /c/Users share, but you need to enter it once and it's kept ;)

source : https://github.com/docker/machine/issues/3908

**Comment by ggajos** [comment]
I've been reading through this pages multiple times and finally found other way around. [I cannot use Hyper-V and native client so I have to stick with the other way which I described here. Maybe would be useful for some of you.](https://medium.com/devopslinks/hey-docker-why-you-hate-windows-so-much-de7a7aa4dd7)

**Comment by KevinGuancheDarias** [comment]
For some reason my /Users folder was not mounted in Windows 7 Docker Toolbox
. I used steps from @juharris  , but I had to add the uid = 1000 and the gid = 50 to avoid permission problems

```
docker-machine.exe ssh default 'sudo mkdir --parents //c/Users'
docker-machine.exe ssh default 'sudo mount -t vboxsf -o umask=0022,gid=50,uid=1000 Users //c/Users'
```
