### ISSUE TITLE
None network with null driver

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#2221]
The default set of networks created on Docker Machine are:

```
docker network ls
NETWORK ID          NAME                DRIVER
1d4d4152b99a        bridge              bridge              
8396171e6bbc        none                null                
8b50dda5fe61        host                host 
```

The "`none`" and "`null`" network seems wrong.

**Comment by dmp42** [comment]
@nathanleclaire wdyt?

**Comment by nathanleclaire** [comment]
I think it's intended behavior of libnetwork.  That's what I get out of the box creating with Machine on an Ubuntu server and we haven't done any funny business setting up the network. @dave-tucker @mavenugo @mrjana let me know if you can confirm/deny this is expected behavior.  Thanks.

**Comment by arun-gupta** [comment]
Not sure if we reached closure on this issue :)

The "`none`" and "`null`" seems wrong independent of the operating system. How should a user interpret them and what are they for?

**Comment by mavenugo** [comment]
@arun-gupta the `none` network is required to provide backward compatibility.... same as we do for `host` and `bridge` network.
this is equivalent to the `--net=none` option that the user is familiar with when running a container using `docker run`.

The reason the driver is called `null` is because, it is a null driver which doesnt do anything (as intended by the user).... the only thing it does is add a loopback interface (again as intended by the user for backward compatibility purposes).

**Comment by nathanleclaire** [comment]
Thanks @mavenugo !
