### ISSUE TITLE
Add documentation page on the `none` driver

### ISSUE THREAD

**Issue by metasim** [docker/machine#2269]
The [list of drivers page](https://docs.docker.com/machine/drivers/) doen't include the `none` driver.

It would also be helpful to have some description of the differences in behavior between `generic` and `none`. I'm struggling in 0.5.0 with adding a manually configured server in my local inventory.

**Comment by jeanlaurent** [comment]
We need to work on the doc on these, you're right.

In the mean time, here's a start of explanation :

The `none` driver is made to be used with an already existing docker host. That's why the driver must run with a `--url` option which should point to the existing docker host.

The `generic` driver purpose is to install a docker host on a machine via ssh.

**Comment by nathanleclaire** [comment]
Yep, @jeanlaurent has it.  `none` is intended to simply add a host which is already existing without doing any transformation to the machine.  `generic` expects parameters for SSH access and will use them to go off and run the usual provisioning process on the target machine (including installing Docker if it isn't around).

I think `none` is a bit broken at the moment, so we're sorry if you've been having issues.  We're working on getting them fixed up and clarifying the use cases in the docs.

**Comment by metasim** [comment]
@nathanleclaire Should this issue be moved to a separate documentation repo, so what @jeanlaurent wrote isn't lost?
