### ISSUE TITLE
Make VirtualBox network configurable

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#24]
At the moment the subnet used by VirtualBox is hard coded. It would be neat if this was configurable, like in boot2docker-cli.

**Comment by ehazlett** [comment]
I think we could do port forwarding but perhaps this is an area for a plugin?  Machine already gives the host only network to avoid the port forwarding issues.  Maybe a plugin would be able to expose it?

**Comment by cwilkes** [comment]
I would like to see this as our company's Cisco VPN client sets up firewall rules which don't know about vboxnetN adapters and thus connections to 192.168.* address are blocked.
However lo* adapter traffic is allowed so if I could get the DOCKER_HOST set to an ip in the 127.0.0.* range then I could easily use machine-docker instead of boot2docker.

**Comment by bergman** [comment]
:+1: This is keeping me on boot2docker due to 192.168.99.x already used in my network.

**Comment by justinclayton** [comment]
+1. same issue as @cwilkes with Cisco AnyConnect VPN. Can't use docker-machine with the certs if I'm to use the workaround listed here: https://github.com/boot2docker/boot2docker/issues/628
