### ISSUE TITLE
Error creating docker-machine create 

### ISSUE THREAD

**Issue by jimitbhalanigsn** [docker/machine#2497]
Hello,

I am using Mac OX 10.10.5. I installed the docker version 1.9.1c.

I am getting the errors on command **docker-machine create -d virtualbox jbhalani-local-dev**

Below is the error I get when I run the command **docker-machine env jbhalani-local-dev**

*Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.*

Please help! Thanks

**Comment by fsoppelsa** [comment]
Have you tried the suggestion there?

**Comment by jimitbhalanigsn** [comment]
yes I tried everything I could. It throws the same timeout error..

**Comment by fsoppelsa** [comment]
Machine version?

**Comment by jimitbhalanigsn** [comment]
You mean docker machine ver? its version 1.9.1c.

**Comment by jimitbhalanigsn** [comment]
This is what I get after I regenerate certificate **docker-machine regenerate-certs jbhalani-local-dev**

*Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>> 
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
*

**Comment by jimitbhalanigsn** [comment]
And this what I get after I run **docker-machine env jbhalani-local-dev**

------------------
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

**Comment by jimitbhalanigsn** [comment]
I have no clue what's wrong. I tried the older version 1.8 of docker and still the same issue. Wonder if there are any network configuration settings that are messed up on my machine

**Comment by fsoppelsa** [comment]
Does `docker-machine ssh dev` work?
Can you check VBoxManage list hostonlyifs active on your system?

**Comment by jimitbhalanigsn** [comment]
Below is what I get on ssh dev

jbhalani2:~ jbhalani$ docker-machine ssh jbhalani-local-dev
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5

**Comment by jimitbhalanigsn** [comment]
jbhalani2:~ jbhalani$ docker-machine ssh jbhalani-local-dev
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5

**Comment by jimitbhalanigsn** [comment]
I am sorry. I did not get your second part. How and where do I check whether VBoxManage list hostonlyifs is active? Thanks!

**Comment by fsoppelsa** [comment]
`yourmac$ VBoxManage list hostonlyifs`

**Comment by jimitbhalanigsn** [comment]
This is what I get

jbhalani2:~ jbhalani$ VBoxManage list hostonlyifs
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

**Comment by jvanoosten** [comment]
I am also using Mac OX 10.10.5 and docker version 1.9.1c.  I see the same problem.   I stopped the  VPNs that I had running and got the same error. 

Creating Machine default...
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting VM...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>> 
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.102:2376": dial tcp 192.168.99.102:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

___________________________________

$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5

________________________________________

$ VBoxManage list hostonlyifs
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.60.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

**Comment by jvanoosten** [comment]
I reinstalled VirtualBox (VirtualBox-5.0.10-104061-OSX.dmg) and docker worked.

Creating Machine default...
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting VM...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect Docker to this machine, run: /usr/local/bin/docker-machine env default
Setting environment variables for machine default...

**Comment by jimitbhalanigsn** [comment]
@jvanoosten Did you remove all traces of previous docker versions like the .docker folder?

**Comment by jvanoosten** [comment]
I only removed the default docker vm before removing VirtualBox.  After reinstalling VirtualBox, I started the Docker Quickstart Terminal and it created the default VM without a problem.   The hello world ran successfully.

**Comment by nathanleclaire** [comment]
When getting regenerate certs error, does re-invoking `docker-machine env default` a few times fix it?

**Comment by jimitbhalanigsn** [comment]
Its finally working. I don't know how. I just reinstalled docker again for the nth time and it worked.

**Comment by nathanleclaire** [comment]
OK, I'm going to close this as we have some similar issues filed for what is probably the problem.  Thanks!

**Comment by Priminus** [comment]
I encountered this on CentOS, and turns out port 2376 was being blocked by the firewall, so I did this.
firewall-cmd --permanent --zone=public --add-port=2376/tcp; systemctl restart firewalld
(not sure why firewall-cmd reload didn't work for me, so I forced a restart)

**Comment by NamPNQ** [comment]
Look like docker not start complete in virtual machine, I get this bug a lot of times

**Comment by ehernandez-xk** [comment]
I have the same issue https://github.com/docker/machine/issues/2590#issuecomment-247650169

**Comment by huyihao** [comment]
I encountered the same problem when connecting to create a docker-machine for ubuntu server.
The problem was finally solved by turning off the firewall by command `sudo ufw disable` in ubuntu.
