### ISSUE TITLE
Update references to Docker Client.

### ISSUE THREAD

**Issue by rolfedh** [docker/machine#2860]
The docker-machine create command ends with the following potentially confusing phrase.
```To see how to connect Docker to this machine, run: docker-machine env local```

Please consider replacing it with the following phrase:
```To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env local```

Similarly, for the output of the following command:
```$ docker-machine env local```

Please consider updating the following line:
```# Run this command to configure your shell ```

To:
```# Run this command to connect your Docker Client to the Docker Engine running on <vmname>.```

**Comment by jeanlaurent** [comment]
Ok for the first part ( done in #2917)

Not ok for the second part, since the action of `docker-machine env local` does not "connect your Docker Client to the Docker Engine" but really configure the shell for enabling it.
Putting a sentence like `# Run this command to configure your shell to enable the connection between your Docker Client to the Docker Engine running on <vmname>.` sounds a bit too verbose.
