### ISSUE TITLE
docker-machine use

### ISSUE THREAD

**Issue by fuse** [docker/machine#2950]
What about having a use command, in charge of doing the eval part ?

Ex:  `docker-machine use awesome-env`

To me it will make more sense, allow easy completion plugin etc…

**Comment by dgageot** [comment]
Hi @fuse, this cannot be done easily because the whole thing is done through env variables and no bash process can change the env variables of its parent process.

However, we provide a wrapper that you can use to achieve this behaviour in `bash`: `contrib/completion/bash/docker-machine-wrapper.bash`

**Comment by fuse** [comment]
Thanks for your reply I'll have a look to use it with zsh.
