### ISSUE TITLE
Virtualbox VM should have 2 cores by default

### ISSUE THREAD

**Issue by jeanlaurent** [docker/machine#2994]

**Comment by nathanleclaire** [comment]
There was quite some discussion about this a while back.  Based on some claims from @SvenDowideit (I forget if it was anecdotal or benchmark), we decided on 1 core instead of the number of available cores on the system (this was the default previously).  I definitely think we should put together some benchmarks / analysis before jumping in to anything.

That said, I definitely think kicking the memory up to 2048 would be a good idea.

**Comment by nathanleclaire** [comment]
Unless I see some benchmarks proving more cores are better, I'm not changing this default.
