### ISSUE TITLE
Interactive shell for docker-machine create

### ISSUE THREAD

**Issue by molivier** [docker/machine#3003]
Wouldn't it be nice to have an interactive shell for `docker-machine create`like:

```
$ docker-machine create --interactive

$ Select a driver: 1

1 - generic
2 - digital ocean
3 - .../...

$ set ip-address: xxx.xxx.xxx.xxx

$ set username (default: root): admin
.../...
```

Maybe it's to complicated too maintain but I was just wondering. Thanks.

**Comment by jeanlaurent** [comment]
Thanks @molivier for the idea, we believe this can be achieved with some sort of wrapper on top of docker-machine a similar to the [docker-machine use](https://github.com/docker/machine/blob/master/contrib/completion/bash/docker-machine-wrapper.bash) command, rather than directly into `docker-machine` code itself.

If you want to contribute such a script, we will be happy to test it and put it in the contrib folder here.
