### ISSUE TITLE
cannot create a digital ocean machine

### ISSUE THREAD

**Issue by eivantsov** [docker/machine#3010]
`C:\Users\Eugene>docker-machine -D create --driver digitalocean --digitalocean-size=4gb --digitalocean-access-token=$token test12`

Results in:

`notifying bugsnag: [Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded]
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded`

Having ssh-ed into this instance, docker ps returned an error. Running Docker daemon manually did not help either.

**Comment by zstarer** [comment]
I think I have the root of this .. I will open a larger item as my failure is on AWS, but I've debugged this to my personal satisfaction.  I have no idea how to fix it though. :)

**Comment by zstarer** [comment]
I've fixed this by upgrading to the latest versions of `docker-machine` and `docker` locally.

when you do `docker-machine ssh test12` can you connect and run `sudo service docker status`?

if you see something like this (**bold for emphasis**) you are experiencing the same thing I did. basically, it looks like `docker -d` was deprecated in favor of a (new to me) `docker daemon` command flag.

  Relevant output on the server:

>> root@Test:/var/log# service docker status
  docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2016-02-07 01:44:21 UTC; 14s ago
  Process: 21577 ***ExecStart=/usr/bin/docker -d*** -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2 (code=exited, status=125)
 Main PID: 21577 (code=exited, status=125)

good luck..

if this doesn't fix your issue, please post us the output of `docker-machine -v` to start with.

**Comment by eivantsov** [comment]
I'll update docker machine, try it again, and then try to ssh into it. Will report back with results. Thanks for your help!

**Comment by kweng2** [comment]
Running into the exact same issue here
```docker-machine -D create --driver digitalocean --digitalocean-access-token=<token> test```
Running that gives me this:
```Running pre-create checks...
Creating machine...
(demo) Creating SSH key...
(demo) Creating Digital Ocean droplet...
(demo) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

After running ```docker-machine ssh test```, then running ```sudo service docker status```, I get this:
```
docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-02-12 02:06:57 EST; 4min 45s ago
  Process: 6225 ExecStart=/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=digitalocean (code=exited, status=125)
 Main PID: 6225 (code=exited, status=125)

Feb 12 02:06:57 test systemd[1]: Started docker.service.
Feb 12 02:06:57 test docker[6225]: flag provided but not defined: -d
Feb 12 02:06:57 test docker[6225]: See '/usr/bin/docker --help'.
Feb 12 02:06:57 test systemd[1]: docker.service: Main process exited, code=exited, ...n/a
Feb 12 02:06:57 test systemd[1]: docker.service: Unit entered failed state.
Feb 12 02:06:57 test systemd[1]: docker.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by andrewsomething** [comment]
What version of docker-machine are you using? Seems to be fixed with 0.6.0:

```
root@docker-sandbox:~# cat /etc/systemd/system/docker.service 
[Service]
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=digitalocean 
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=

[Install]
WantedBy=multi-user.target
root@docker-sandbox:~# logout
```

```
asb@asb-laptop:~$ docker-machine -v
docker-machine version 0.6.0, build e27fb87
```

In this commit: https://github.com/docker/machine/commit/28b2fe9ce054d482be0174e5493274f1eab08108 PR: https://github.com/docker/machine/pull/2844

**Comment by nathanleclaire** [comment]
Please re-open if you encounter any issues

**Comment by andrescabana86** [comment]
Same issue on Digital Ocean
`
root@nubiguia-troubleshooting-web-static:~# service docker start
root@nubiguia-troubleshooting-web-static:~# service docker status
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Tue 2018-04-24 01:11:09 UTC; 4s ago
  Process: 1708 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:/
 Main PID: 1708 (code=exited, status=125)

Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   tag         
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   top         
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   unpause     
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   update      
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   version     
Apr 24 01:11:09 nubiguia-troubleshooting-web-static systemd[1]: docker.service: 
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]:   wait        
Apr 24 01:11:09 nubiguia-troubleshooting-web-static docker[1708]: Run 'docker CO
Apr 24 01:11:09 nubiguia-troubleshooting-web-static systemd[1]: docker.service: 
Apr 24 01:11:09 nubiguia-troubleshooting-web-static systemd[1]: docker.service: `
