### ISSUE TITLE
docker-machine upgrade to 1.10; containers did not start again

### ISSUE THREAD

**Issue by schmunk42** [docker/machine#3013]
I have done a `docker-machine upgrade ...` on a machine with one container with policy `restart: always`, but after the upgrade there were no containers running at all.

I'd have expected that my containers start, like they do when I am restarting a machine

```
docker-machine -v
docker-machine version 0.4.0 (9d0dc7a)
```

**Comment by nathanleclaire** [comment]
Can you please trying Docker Machine version 0.6.0?

Also, it's possible this might be related to the 1.10 image layer migration (which will hang the existing daemon for some time when upgrading).

**Comment by schmunk42** [comment]
Will report when I have the chance to try it again.

**Comment by nathanleclaire** [comment]
I think upgrade requires a power cycle of the daemon right now unfortunately.  So, I'm not sure there's anything actionable on this issue, since any containers run without `--restart always` will not come back up. However, I'm not sure if the recent `runc` changes might help with this.  It's certainly worth looking into.
