### ISSUE TITLE
Enhancement: Grow to use more host fs space

### ISSUE THREAD

**Issue by mcandre** [docker/machine#3048]
docker-machine's disk space can become too low to function properly, even though the host has plenty of free space. Please let docker-machine's virtual disk grow as it fills.

**Comment by jeanlaurent** [comment]
On virtualbox, and most probably under fusion too, there is no such thing as dynamically growing disk size. I suspect this is because most OS's or filesystems could not cope with a disk drive with a variable capacity.

You can either choose a "big enough" disk size, or fiddle with external tools to grow the capacity of your current disk size, and set another, bigger, limit.

Note that the disk from the host point of view is significantly smaller than the actual disk size reported in the guest, so you can probably use bigger disk size without filling your host system disk.

**Comment by nathanleclaire** [comment]
The VirtualBox disk created is a "dymamically growing" drive already, so if you want more space, I'd suggest just creating your machines with `--virtualbox-disk-size` set to `100000` or however much you'd like to allocate.  The VM won't actually use that much space until it's needed _but_ once it's used, the host OS won't be able to reclaim it until the virtual disk is destroyed.
