### ISSUE TITLE
docker-machine vs sudo docker-machine

### ISSUE THREAD

**Issue by joergd** [docker/machine#3127]
When I run

    docker-machine active

I get the active machine.

If I run
     
    sudo docker-machine active

I get "no active host found".

The same with

    docker-machine inspect dinghy

and

    sudo docker-machine dinghy

I am using dinghy to manage my docker environment on Mac OS X - and the dinghy command requires docker-machine to be elevated to sudo when running commands - but unfortunately the sudo and non-sudo commands return different results.

Is there anything I can change on my setup so that the same output is returned? Is something wrong on my end? Where can I change right etc to make this work properly? Or is this by design?

**Comment by thieman** [comment]
(Disclaimer: not a maintainer, might want to fact check me on some of this)

Machine operates on the user level by design. It stores a lot of state in `~/.docker/machine` for each user, including which machines it has defined, certificates for connecting to them, etc. If dinghy requires everything to run as `root`, then the machine you're operating on must also be owned by the `root` user.

We have a similar problem in [Dusty](http://dusty.gc.com) where we need some root privileges but also want to be able to use a non-root user's machine. We solved this by specifying the user who owned the machines and dropping privileges down to that user whenever we wanted to talk to Machine. Dinghy might need to implement this pattern to avoid having to run everything as root.

**Comment by joergd** [comment]
Ok awesome thank you.

**Comment by nathanleclaire** [comment]
Yes, Machine itself is not meant to be run as root.  I'd suggest if users need to `sudo` operations related to Machine (such as setting up NFS mounts) that they take a similar approach to what [Vagrant has done](https://www.vagrantup.com/docs/synced-folders/nfs.html) by creating custom sudoers entries for those commands.
