### ISSUE TITLE
Default distro image for cloud drivers?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#3177]
I realized gce driver uses ubuntu 15.10 image: https://github.com/docker/machine/blob/5a270c975123e00bd42a385ccd36501c20f7a3d7/drivers/google/google.go#L37 and I remember I got a PR rejected when I tried to upgrade to a version other than 14.04. Do we have a guideline about what should be the "default distro image" for cloud drivers?

**Comment by nathanleclaire** [comment]
It's 15.10 currently, although it's been a more implicit rule than explicit.  We may have rejected the PR due to not being prepared for systemd on Ubuntu, which we now have made some changes to support.  So, we'd be happy to bump it for any driver you like.  Maybe we should add some additional docs outlining this expectation as well.

**Comment by ahmetalpbalkan** [comment]
hmm digitalocean uses 15.10 too https://github.com/docker/machine/blob/5a270c975123e00bd42a385ccd36501c20f7a3d7/drivers/digitalocean/digitalocean.go#L38. I can't locate amazonec2's `ami-615cb725`  on Canonical's AMI Locator. https://cloud-images.ubuntu.com/locator/ec2/.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire alright let me quickly fix this in Azure PR, too.
