### ISSUE TITLE
Add DOCKER_IP env variable to docker-machine env output

### ISSUE THREAD

**Issue by tsgautier** [docker/machine#3216]
It would be nice if there were a standard env variable that held the IP address of the host.  This would help in setting up services that talk to docker containers running inside the docker host on mapped ports other than the one used by docker machine and exported via DOCKER_HOST.

I would propose DOCKER_IP (since DOCKER_HOST is already used)

**Comment by nathanleclaire** [comment]
Why not just `$(docker-machine ip name)`?

**Comment by tsgautier** [comment]
Because you can't $(docker-machine ip name) in a config file.  So that means if I want to specify the docker ip in a config file, I need to 
$ export SOME_VAR=$(docker-machine ip name)

``` in some config file
value=${SOME_VAR}
```

And that leads to the name SOME_VAR not being standard, which is why I proposed this feature in the first place, so it could be a standard name supported by the docker tool itself instead of leaving it unspecified.

**Comment by nathanleclaire** [comment]
I don't understand.  You would need to run `eval $(docker-machine env name)` to set the proposed `DOCKER_IP` to the correct value, right?  So what would be better about running `eval $(docker-machine env name)` versus running `export DOCKER_IP=$(docker-machine ip name)`?

**Comment by tsgautier** [comment]
Sorry, I would rather run 

eval ($docker-machine env)

Which will set everything.  Then, I won't be the one inventing the name DOCKER_IP.  It would be standard, and every tool could rely upon it that assumes you've already done the above command (which, already sets things like DOCKER_HOST, DOCKER_MACHINE_NAME, etc.).  My proposal is to add one variable to the output of docker-machine env:

Instead of : 

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="<path>"
export DOCKER_MACHINE_NAME="<name>"
```

It is:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_IP="192.168.99.100"
export DOCKER_CERT_PATH="<path>"
export DOCKER_MACHINE_NAME="<name>"
```

This is because DOCKER_HOST isn't an IP address, so the format is usable by the docker process to know where the docker host is, because it expects a uri, but not every config/tool expects or wants a uri.  

Imagine you want to construct a URL to a service running in a container on the docker host, with my proposal, it would be https://${DOCKER_IP}/my/service" (after having run `eval $(docker-machine env)` of course, and without my proposal, it's effectively impossible to do so without some _additional_ (and non-standard) post-processing.

**Comment by tsgautier** [comment]
Incidentally, perhaps DOCKER_HOST_IP is a better name.

**Comment by nathanleclaire** [comment]
What happens if you set `DOCKER_HOST_IP`, but the IP address changes on the remote instance?  e.g. through a `stop` and `start`?  Why not use the command which will always(ish) be consistent instead of relying on an environment variable that could drift from the true value?

**Comment by tsgautier** [comment]
Then the value is out of date - no different than how it would be now for DOCKER_HOST or any other variable.

The gist of this request really boils down to - I don't want to have to write specific custom parsing to pluck the actual IP address out of the DOCKER_HOST variable.  Doesn't it seem reasonable to have that separate?

**Comment by nathanleclaire** [comment]
> The gist of this request really boils down to - I don't want to have to write specific custom parsing to pluck the actual IP address out of the DOCKER_HOST variable. Doesn't it seem reasonable to have that separate?

Isn't it separate already today, in the `docker-machine ip` command?  Why put it all in one command?

**Comment by tsgautier** [comment]
Ok, we've begun to go in a circle.  I already answered that question.  So it would have a consistent name.  

Thanks for rejecting.

**Comment by AstraSerg** [comment]
I'm trying to create conpose file for consul and it would help, if I have machine's IP in an env variable. For example the **advertise** option takes IP-addresses only.

**Comment by edmorley** [comment]
I was about to open an issue for this, could this be reopened?

If it helps, here's a more detailed use case:
* Even in development, Django requires that the hostname for inbound requests either be localhost/127.0.0.1 or else be explicitly whitelisted via the `ALLOWED_HOSTS` setting (to avoid DNS rebinding attacks).
* This is no problem when the Docker host OS is Linux, or when using the new "Docker for Windows/Mac", since they automatically configure port forwarding, so one can just connect to `localhost:8000`, which Django accepts.
* However when using Docker Machine with boot2docker in Virtualbox, no automatic port forwarding takes place (#4115), which means you have to connect to `$DOCKER_VM_NAT_IP:8000` instead, which requires adding the IP to `ALLOWED_HOSTS`.
* Since I'm using Docker Compose, I need to set `ALLOWED_HOSTS` in `docker-compose.yml`, which doesn't support the use of shell commands to set variables, so I can't just use `ALLOWED_HOSTS=$(docker-machine ip)`. The Docker compose syntax only supports a subset of the Bash string substitutions, so I can't even try to trim the `tcp://` and port from the existing `DOCKER_HOST` variable (set by `eval $("docker-machine env)`) like I might in a bash script.
* As such the only workaround I have is to pass `DOCKER_HOST` verbatim in the docker compose config, and in Python extract the IP to pass to `ALLOWED_HOSTS`, which then means adding Docker development specific code to the Django config, which is unnecessary boilerplate and contrary to the [12-factor app](https://12factor.net/) methodology.

If `eval $("docker-machine env)` made the IP available, the above wouldn't be necessary. 

Someone opened a PR for this (#3057), however it was wontfixed without considering the Docker Compose case (where shell expansions cannot be used).

**Comment by edmorley** [comment]
Ah meant to add: another workaround would be adding `export DOCKER_HOST_IP="$(docker-machine ip)"` to my bash profile, however that doesn't help for a docker-compose config intended to be consumed by other developers, since now the project contribution documentation has yet another manual step rather than just "install docker and run docker-compose up".
