### ISSUE TITLE
``machine provision`` should allow to change options.

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/machine#3237]
``machine provision`` command should allow docker engine and swarm options.

It will be helpful to use same docker host with environment changes like proxy servers etc.

**Comment by nathanleclaire** [comment]
I agree that would be really nice.

It is a hack, but today it is actually possible to do this by editing the Machine's `config.json` and calling `docker-machine provision` on it.

I'm hopeful that someday we can detangle calculated machine properties such as public IPv4 address from the "desired config" , so that it could be exposed to the end user and made first-class in some form.

**Comment by kunalkushwaha** [comment]
>It is a hack, but today it is actually possible to do this by editing the Machine's config.json and calling >docker-machine provision on it.

Thanks for this info. It will save lot of my time :) 
I think, this could be mentioned in [Provision docks] (https://docs.docker.com/machine/reference/provision/) with a _Warning Note_

**Comment by nathanleclaire** [comment]
Since it gets into using plumbing to accomplish "real work", I'm a bit hesitant, since I don't want users to rely on plumbing that might change.  However, since I do feel the feature could be very useful, I will strongly keep it in mind for the future.

Since it's "resolved", I'm going to go ahead and close this issue.
