### ISSUE TITLE
"Storage > SSD" VirtualBox Option causes error

### ISSUE THREAD

**Issue by thinking-aloud** [docker/machine#3307]
Hi,
I have Docker 1.11 and when I enable the "Solid-state Drive" option in the storage section of the docker VM I get "java.net.SocketTimeoutException" on all my Java containers. The other containers don't work aswell.
removing the option fixes it.

**Comment by nathanleclaire** [comment]
Hi @thinking-aloud, thanks for the issue.

Since this gets into what I call "warranty voiding" turf (i.e. custom modifications not in the prescribed Machine workflow), I'm going to close the issue, but thank you for bringing it to our awareness.

Does virtualized SSD have better performance if using a real SSD drive?  What's the motivation?
