### ISSUE TITLE
is there have a way use socks proxy 

### ISSUE THREAD

**Issue by wxd237** [docker/machine#3325]
fucking Great Fire Wall of China,we can't download Boot2Docker ISO
is there have a way use socks proxy

**Comment by nathanleclaire** [comment]
> fucking Great Fire Wall of China,we can't download Boot2Docker ISO

:(

> is there have a way use socks proxy

In Machine directly, unless I am mistaken we unfortunately do not support `socks5://` protocol (this was just added by Docker client though, so that's nice -- I would be happy to accept PR to support `ALL_PROXY` in the same manner).  Just normal HTTP proxy.

However, if you have a SOCKS proxy available, you could route your entire system through it, and then Docker Machine should work.  I've done that on my Mac using Network Settings.
