### ISSUE TITLE
Shell connection eval statement does not propagate exit status

### ISSUE THREAD

**Issue by cjerdonek** [docker/machine#3331]
The [Docker Machine docs](https://docs.docker.com/machine/get-started/#create-a-machine) say to do the following to connect your shell to a machine:

    $ eval "$(docker-machine env default)"

However, one deficiency with this is that it doesn't propagate the correct exit status if the `docker-machine env` invocation fails. To see this for yourself, you can execute the following:

    $ eval "$(docker-machine env bad_name)"; echo $?
    Error trying to get host "bad_name": Loading host from store failed: Host does not exist: "bad_name"
    0

One possible solution would be to recommend the following variation instead:

    $ eval 'out="$(docker-machine env default)"'

Then you would have--

    $ eval 'out="$(docker-machine env default)"'; echo $?
    0
    $ eval 'out="$(docker-machine env bad_name)"'; echo $?
    Error trying to get host "bad_name": Loading host from store failed: Host does not exist: "bad_name"
    1

This work-around is documented [here](http://unix.stackexchange.com/a/23099), for example, where it says, "a way to take the exit status into account is to use the command substitution in a simple assignment: then the exit status of the assignment is the exit status of the last command substitution in the assignment(s)."

I think this would help because this assignment work-around isn't so obvious and easy to find. It would be especially helpful in a scripting context.

**Comment by nathanleclaire** [comment]
Hi @cjerdonek, thanks for the issue.

While I agree with the principle of the idea, in my experience having to remember and type correctly `eval $(docker-machine env name)` has already proven to be at the limit of what people are willing to tolerate.

In general, if the command in the subshell is successful, it will not print any output (to STDERR), but otherwise it will.  This is historically how we indicate this to the user.

You can, of course, still use your method in your own scripts.
