### ISSUE TITLE
Default memory for virtualbox machine is too low

### ISSUE THREAD

**Issue by pkqk** [docker/machine#3432]
The default memory size for a VM appears to be 1024MB [here](https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L25).

This creates hard to understand errors on complex container setups as processes keep getting killed by the OOM killer.

**Comment by StefanScherer** [comment]
@pkqk You don't have to go so deep into the sources to lookup the default. Just show the usage for each driver with

```
docker-machine create -d virtualbox --help
```

Just create a bigger machine if you need more RAM.

**Comment by nathanleclaire** [comment]
Yes, today the default is attempting a happy medium, since some users may be on pretty underpowered devices, historically I have been hesitant to kick up the defaults.  Toolbox does use 2GB by default so I don't feel strongly we need to configure this at the Machine level.  As @StefanScherer noted, `--virtualbox-memory` will treat you well :)
