### ISSUE TITLE
docker-machine amazonec2 driver fails with "The spot instance request ... does not exist" error when creating spot instance

### ISSUE THREAD

**Issue by spingel** [docker/machine#3539]
> $ docker-machine create --driver amazonec2 --amazonec2-request-spot-instance --amazonec2-spot-price 0.05 --engine-label "tag=test" docker-host-26188
> Creating machine...
> (docker-host-26188) Launching instance...
> (docker-host-26188) Waiting for spot instance...
> Error creating machine: Error in driver during machine creation: Error fulfilling spot request: InvalidSpotInstanceRequestID.NotFound: The spot instance request ID 'sir-03hedbf4' does not exist
>     status code: 400, request id: 

The spot request is however visible in the AWS console and a machine is provisioned. If we try to remove the docker machine again this also fails and leaves the instance running:

> $ docker-machine rm -f docker-host-26188
> About to remove docker-host-26188
> Error removing host "docker-host-26188": unknown instance
> MissingParameter: The request must contain the parameter KeyName
>     status code: 400, request id: 

We have added some manual clean up to make sure the spot request is cancelled in those cases but it would be nice if docker-machine could just retry getting the spot request a few times:

> $ aws ec2 cancel-spot-instance-requests --spot-instance-request-ids sir-03hedbf4
> Cancelling spot request: sir-03hedbf4
> {
>     "CancelledSpotInstanceRequests": [
>         {
>             "State": "cancelled", 
>             "SpotInstanceRequestId": "sir-03hedbf4"
>         }
> }

**Comment by dinusubba** [comment]
I am facing this error too. This is becoming more common when we are trying to provision multiple machines.

**Comment by chillosu** [comment]
Seeing this error as well on a daily basis and is impacting our workflow.

**Comment by ppostma** [comment]
I was seeing this error as well and believe this is related to [Amazon's Eventual Consistency model](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency).

To test this, I’ve added a 5 second sleep between the calls to `RequestSpotInstances` and `WaitUntilSpotInstanceRequestFulfilled`. Since then (testing for about 2 weeks now), I’ve not seen these errors anymore.

Unfortunately, I don’t have enough knowledge of Go to fix this properly (by implementing some kind of retry mechanism). But maybe this will trigger someone to implement a real fix…

**Comment by chillosu** [comment]
Thanks for the insight here, anyway to bump up this priority?

**Comment by nolith** [comment]
Thank @ppostma for the hint. I've created a PR #4312 based on your findings.
