### ISSUE TITLE
Feature Request: Suggest `docker-machine upgrade` when appropriate

### ISSUE THREAD

**Issue by b-long** [docker/machine#3670]
It seems like @nathanleclaire 's comment on the thread "_**Error response from daemon: client is newer than server**_" ([here](https://github.com/docker/machine/issues/2147#issuecomment-153521326)) is the important step that many docker machine user's take in order to resolve the following error : 

```
docker: Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23).
See 'docker run --help'.
```

Since we can detect `client is newer than server` , I wonder if it might be useful to modify the output to suggest the user run `docker-machine upgrade`.  Has this been considered?

**Comment by nathanleclaire** [comment]
Thanks for the suggestion -- It would have to go in upstream docker/docker and probably a bit out of scope for the Docker CLI since the remote daemon you are attempting to connect to is not necessarily a Docker Machine VM.  e.g., it might be a newer Linux binary connecting to an older Linux daemon all on the same OS.
