### ISSUE TITLE
Proposal to make hostname override optional 

### ISSUE THREAD

**Issue by wlan0** [docker/machine#3709]
Similar request in this Issue https://github.com/docker/machine/issues/3696, I would like to propose a flag `disable-hostname-override`, when set, will disable the hostname override by docker-machine. 

At rancher, we need this because we use docker-machine to provision hosts for our Kubernetes setup, and Kubernetes requires hosts to use their cloud specific hostnames for its operations (mounting ebs volumes, etc...). Since Kubernetes identifies hosts in the cloud provider using their hostname, it is unable to identify hosts provisioned with docker-machine, as their hostnames have been overridden.

**Comment by bamarni** [comment]
This is also problematic for the raspberry integration, as it leaves the avahi deamon with an outdated config for mDNS (to access the machine through `{hostname}.local`).

Instead of an explicit flag to disable this, what about disabling this by default in the case of the `generic` driver? And maybe a flag to enable this, but for an existing machine changing the hostname is somehow unexpected imo.

**Comment by wlan0** [comment]
@bamarni - I wanted the hostname to be set by default, because that is the existing behavior. Adding a flag to override that behavior ensures that existing behavior is consistent with new behavior, and anyone changing it is doing so explicitly.

**Comment by wlan0** [comment]
@SvenDowideit @nathanleclaire what are your thoughts?

**Comment by nathanleclaire** [comment]
I'm not opposed to the general idea of selectively opting out of provisioning steps (some operators have expressed distress at automatic `update` of packages for instance), but it's potentially quite tricky to add.

What I'd prefer to see, vs. just one flag, is maybe some kind of `StringSlice` flag, e.g. `--prov-skip`, which could be used to conditionally specify steps of provisioning to skip over. e.g.

```console
$ docker-machine create -d amazonec2 \
    --prov-skip pkg-update \
    --prov-skip hostname \
    foo
```

Tricky though, since provisioners have really blown up in scope and we're being bitten by our lax attitude towards code duplication in that section of the code base.  To create such a change we need consistency across provisioners as a requirement.

As for the rPi/avahi thing, that's unfortunate to hear.  Can you `SIGHUP` avahi or anything like that to reload the hostname?

**Comment by SvenDowideit** [comment]
I've kinda avoided using the generic driver - because i don't know what its going to change - I'd certainly be unhappy if using machine on an existing box changes its hostname :)

**Comment by bamarni** [comment]
@wlan0 : indeed I was suggesting a BC break, the question is, is changing the hostname part of the provisioning process or is it part of the machine creation? I'd be tempted to say it's the latter.

**Comment by SvenDowideit** [comment]
I've kinda avoided using the generic driver - because i don't know what its going to change - I'd certainly be unhappy if using machine on an existing box changes its hostname :)
