### ISSUE TITLE
Docker AWS Provisioning Issue - Cannot Create Swarm Master AWS instance with External Key/Value Store - Needed for Overlay Networking

### ISSUE THREAD

**Issue by mhockelberg** [docker/machine#3855]
I am working through the Overlay portion of this example:  https://docs.docker.com/engine/userguide/networking/get-started-overlay/ and I am getting an error (see below).

I am using Docker for Mac, my Mac environment:

{"Client":{"Version":"1.12.2","ApiVersion":"1.24","GitCommit":"bb80604","GoVersion":"go1.7.1","Os":"darwin","Arch":"amd64","BuildTime":"Sun Oct 16 07:57:31 UTC 2016"},"Server":null}

NOTE:  I had a colleague try this same build on their AWS and they ran it with Docker installed on an Ubuntu instance they had running on a VM, they received the same error.

**Terminal Output with Error:**

docker-machine create \
>  -d amazonec2 \
>  --swarm --swarm-master \
>  --swarm-discovery="consul://$(docker-machine ip my-keystore):8500" \
>  --engine-opt="cluster-store=consul://$(docker-machine ip my-keystore):8500" \
>  --engine-opt="cluster-advertise=eth1:2376" \
>  --amazonec2-region us-east-1 \
>  --amazonec2-instance-type c3.2xlarge \
>  --amazonec2-ami ami-2d39803a \
>  --amazonec2-access-key **************** --amazonec2-secret-key *************** \
>  swarm-master
Running pre-create checks...
Creating machine...
(swarm-master) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(upstart)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring swarm...
Error creating machine: Error running provisioning: Unable to pull image: Post https://52.201.x.x:2376/v1.15/images/create?fromImage=swarm%3Alatest: read tcp 192.168.x.x:59968->52.201.x.x:2376: read: connection reset by peer

Has anyone else run into this?  The pull request always fails and I am not sure where to go from here.  Any help is appreciated at this point.

Thanks,
Monica

**Comment by mhockelberg** [comment]
This specific issue was caused by the naming of the ethernet interface on the AWS instance.  

Changing from: eth1 to ens3 solved the problem (see modified command below).

docker-machine create \
-d amazonec2 
--swarm --swarm-master 
--swarm-discovery="consul://$(docker-machine ip my-keystore):8500" 
--engine-opt="cluster-store=consul://$(docker-machine ip my-keystore):8500" 
--engine-opt="cluster-advertise=ens3:2376" 
--amazonec2-region us-east-1 
--amazonec2-instance-type c3.2xlarge 
--amazonec2-ami ami-2d39803a 
--amazonec2-access-key **************** --amazonec2-secret-key *************** 
swarm-master

**Comment by mrmahesh** [comment]
$ docker-machine create \
>  -d virtualbox \
>  --swarm --swarm-master \
>  --engine-env NO_PROXY=localhost,.us.oracle.com,.oraclecorp.com,.oracle.com \
>  --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
>  --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
>  --engine-opt="cluster-advertise=eth1:2376" \
>  mgr
Running pre-create checks...
(mgr) Unable to get the latest Boot2Docker ISO release version:  Get https://api.github.com/repos/boot2docker/boot2docker/releases/latest: dial tcp 192.30.253.116:44
3: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because conne
cted host has failed to respond.
Creating machine...
(mgr) Unable to get the latest Boot2Docker ISO release version:  Get https://api.github.com/repos/boot2docker/boot2docker/releases/latest: dial tcp 192.30.253.116:44
3: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because conne
cted host has failed to respond.
(mgr) Copying C:\Users\mrmahesh\.docker\machine\cache\boot2docker.iso to C:\Users\mrmahesh\.docker\machine\machines\mgr\boot2docker.iso...
(mgr) Creating VirtualBox VM...
(mgr) Creating SSH key...
(mgr) Starting the VM...
(mgr) Check network to re-create if needed...
(mgr) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring swarm...
Error creating machine: Error running provisioning: Unable to pull image: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connecti
on (Client.Timeout exceeded while awaiting headers)
