### ISSUE TITLE
Volume mounts not working with digital ocean.

### ISSUE THREAD

**Issue by richmidwinter** [docker/machine#3982]
Small test case:

docker-compose.yml
```
nginx:
  image: nginx:1
  ports:
    - "80:80"
  volumes:
    - ./testconf:/etc/nginx/conf.d
    - ./testhtml:/usr/share/nginx/html
```

testconf/nginx.conf
```
server {
  listen        80;
  server_name _;

  location / {
    root /usr/share/nginx/html;

    try_files $uri $uri/;
  }
}
```

testhtml/index.html
```
<!DOCTYPE html>
<html>
  <body>
    <p>Hello</p>
  </body>
</html>
```

```
$ docker-machine create --driver digitalocean --digitalocean-access-token xxxx --digitalocean-region "ams3" edgee
$ eval $(docker-machine env edgee)
$ docker-compose up
$ curl $(docker-machine ip edgee)
curl: (7) Failed to connect to xxx.xx.xxx.xxx port 80: Connection refused
```

When I look inside the container the files which should be mounted just aren't there. This works locally, it works with machine and virtualbox, but it doesn't work with digitalocean?

**Comment by nathanleclaire** [comment]
It's expected behavior. Bind mount means to mount the path from the Docker daemon's computer (droplet) host FS to the container FS, not from the client computer (mac/windows). It can't really work over the network. machine/virtualbox etc. "cheat" by mounting in the whole of `/Users` (or equivalent) to the VM at startup using VBox shared folders. This makes it look transparent but it's not a true remote mount.

**Comment by euri16** [comment]
@nathanleclaire so how we upload our static files then?

**Comment by nathanleclaire** [comment]
`docker-machine scp`, or `rsync` with the machine's SSH key stored in `~/.docker/machine` should do

**Comment by antonpegov** [comment]
You should remove volumes from docker-compose and create separate Dockerfile (and change 'image' on 'build') for running your nginx container. Inside it just copy needed files. Something like 
`FROM nginx
ADD testconf /etc/nginx/conf.d
ADD testhtml /usr/share/nginx/html`
