### ISSUE TITLE
I can't create my docker-machine with digitalocean (ubuntu)

### ISSUE THREAD

**Issue by HansFenix127** [docker/machine#4015]
Today my docker installation asked me if i want to upgrade to docker 17. I click "in remember me later," but i have the same error. I upgrade and have the same error. 

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## The command
docker-machine create --driver=digitalocean \
--digitalocean-access-token $DO_TOKEN \
--digitalocean-image ubuntu-16-04-x64 \
--digitalocean-region nyc3 \
--digitalocean-size 512mb \
--digitalocean-ipv6 \
--digitalocean-private-networking \
--digitalocean-ssh-key-fingerprint $DO_FPRINT \
machine-name

## Output
Running pre-create checks...
Creating machine...
(padduk-production) Creating SSH key...
(padduk-production) Assuming Digital Ocean private SSH is located at ~/.ssh/id_rsa
(padduk-production) Creating Digital Ocean droplet...
(padduk-production) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

## SSH in the machine and type
`$ journalctl -xe`

```
Unit docker.service has begun starting up.
Mar 03 20:38:45 padduk-production docker[6060]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` dir
Mar 03 20:38:45 padduk-production docker[6060]: time="2017-03-03T20:38:45.786811228Z" level=info msg="libcontainerd: new containerd process,
Mar 03 20:38:45 padduk-production docker[6060]: Error starting daemon: error initializing graphdriver: driver not supported
Mar 03 20:38:45 padduk-production systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 20:38:45 padduk-production systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Mar 03 20:38:45 padduk-production systemd[1]: docker.service: Unit entered failed state.
Mar 03 20:38:45 padduk-production systemd[1]: docker.service: Failed with result 'exit-code'.
```

Can anybody help me?

**Comment by xxradar** [comment]
I experiencing the same .. ticket is logged.  Problem is related to the --storage-driver ... if I ommit the flag, docker is starting ... keep you updated.

**Comment by xxradar** [comment]
systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: failed (Result: exit-code) since Fri 2017-03-03 22:48:27 UTC; 4min 52s ago
     Docs: https://docs.docker.com
  Process: 5542 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server
 Main PID: 5542 (code=exited, status=1/FAILURE)

Mar 03 22:48:27 supporttest systemd[1]: Starting Docker Application Container Engine...
Mar 03 22:48:27 supporttest docker[5542]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Mar 03 22:48:27 supporttest docker[5542]: time="2017-03-03T22:48:27.094530813Z" level=info msg="libcontainerd: new containerd process, pid: 5550"
Mar 03 22:48:27 supporttest docker[5542]: Error starting daemon: error initializing graphdriver: driver not supported
Mar 03 22:48:27 supporttest systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 22:48:27 supporttest systemd[1]: Failed to start Docker Application Container Engine.
Mar 03 22:48:27 supporttest systemd[1]: docker.service: Unit entered failed state.
Mar 03 22:48:27 supporttest systemd[1]: docker.service: Failed with result 'exit-code


root@supporttest:/etc/docker# /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem 
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
INFO[0000] libcontainerd: new containerd process, pid: 5892 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
Error starting daemon: error initializing graphdriver: driver not supported

w/o the driver flag 
root@supporttest:/etc/docker# /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem 
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
INFO[0000] libcontainerd: new containerd process, pid: 5910 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
INFO[0000] [graphdriver] using prior storage driver: overlay2 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
WARN[0000] Your kernel does not support swap memory limit 
WARN[0000] Your kernel does not support cgroup rt period 
WARN[0000] Your kernel does not support cgroup rt runtime 
INFO[0000] Loading containers: start.                   
INFO[0000] Firewalld running: false                     
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=60ccb22 graphdriver=overlay2 version=17.03.0-ce
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] API listen on [::]:2376

**Comment by nathanleclaire** [comment]
I can dupe. Looking into it

**Comment by nathanleclaire** [comment]
For some reason, the `get.docker.com` script seems to not properly install AUFS. Maybe because `linux-image-extra-4.4.0-65-generic` package isn't present.

**Comment by nathanleclaire** [comment]
Argh, this is why. I wonder if it's DigitalOcean's mirrors causing issue.

```
+ sh -c sleep 3; apt-get install -y -q linux-image-extra-4.4.0-65-generic linux-image-extra-virtual
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-image-extra-4.4.0-65-generic
E: Couldn't find any package by glob 'linux-image-extra-4.4.0-65-generic'
E: Couldn't find any package by regex 'linux-image-extra-4.4.0-65-generic'
modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-65-generic
Warning: tried to install linux-image-extra-4.4.0-65-generic linux-image-extra-virtual (for AUFS)
 but we still have no AUFS.  Docker may not work. Proceeding anyways!
```

**Comment by nathanleclaire** [comment]
We'll work internally and/or with DO on resolving this. In the interim, `overlay2` should be pretty decent storage driver these days, give it a whirl ;)

**Comment by HansFenix127** [comment]
Thanks !!
