### ISSUE TITLE
boot2docker alternative? 

### ISSUE THREAD

**Issue by tyler-thetyrant** [docker/machine#4109]
Is there a way to deploy a custom dockerfile/container to my machine driver (vsphere) instead of default boot2docker? I couldn't find any subcommands for it.

**Comment by SvenDowideit** [comment]
machine is for deploying small OS's - so yes, but you need to make a bootable iso for it

for example, I use machine to do RancherOS testing, so use 

```
~/bin/machine -D create --driver vmwarevsphere \
	--vmwarevsphere-vcenter 10.10.10.2 \
	--vmwarevsphere-boot2docker-url rancheros.iso \
	 $@
```

when I have a rancheros.iso in the dir i'm running from (otherwise, it can also be a URL...

this works for most drivers (and I'll continue to fix those that cause me issues)

**Comment by tyler-thetyrant** [comment]
Thank you for your comment!
