### ISSUE TITLE
SSH timeout on machine create OSX, VMWare Fusion

### ISSUE THREAD

**Issue by mafrosis** [docker/machine#4137]
I tried with `0.12.0` from Homebrew, and then the latest `rc2` from master. Neither finish and connect SSH.

    mafro@takeshi:~ > docker-machine --version
    docker-machine version 0.12.0-rc2, build 64fa459
    mafro@takeshi:~ > docker-machine create portal
    Running pre-create checks...
    (portal) Default Boot2Docker ISO is out-of-date, downloading the latest release...
    (portal) Latest release for github.com/boot2docker/boot2docker is v17.06.0-ce-rc3
    (portal) Downloading /Users/mafro/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.06.0-ce-rc3/boot2docker.iso...
    (portal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
    Creating machine...
    (portal) Copying /Users/mafro/.docker/machine/cache/boot2docker.iso to /Users/mafro/.docker/machine/machines/portal/boot2docker.iso...
    (portal) Creating SSH key...
    (portal) Creating VM...
    (portal) Creating disk '/Users/mafro/.docker/machine/machines/portal/portal.vmdk'
    (portal) Virtual disk creation successful.
    (portal) Starting portal...
    (portal) Waiting for VM to come online...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

Full log with `--debug` can be found in this gist: 
https://gist.github.com/mafrosis/620ccf4aefcbef5d27c32fa76351a12e

**Comment by damianopetrungaro** [comment]
I have the same issue.
Any workaround?

**Comment by mafrosis** [comment]
@damianopetrungaro sorry missed the notification. I rolled back to previous version with a manual install:

    curl -L https://github.com/docker/machine/releases/download/v0.11.0/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine

**Comment by damianopetrungaro** [comment]
@mafrosis thank you 😄 

I would not like to rollback i'll wait another week, otherwise rollback is the better solution atm.

**Comment by cmrigney** [comment]
I'm experience the exact same issue as well.  I'll try the rollback for now.

**Comment by pphetra** [comment]
I think the problem is cause by this [commit](https://github.com/docker/machine/commit/39e6b192a6bc179f398af7bfe3e7b309596d8122).  My guess is that the second "runScriptInGuest" command (that try to move userdata.tar to /var/lib/boot2docker/)  is successfully execute before the first one. These are error messages that is in /var/log/userdata.log.

**Comment by pphetra** [comment]
The problem is not in the second "runScriptInGuest". But it 's in tar command. It 's should be

`sudo sh -c \"tar xvf /home/docker/userdata.tar -C /home/docker ` 

instead of 

`tar xvf userdata.tar -C /home/docker`

I have successfully test this patch on my machine.

**Comment by mafrosis** [comment]
@pphetra Are you saying that `userdata.tar` should be `/home/docker/userdata.tar` in 39e6b192a6bc179f398af7bfe3e7b309596d8122 ?

**Comment by mafrosis** [comment]
The diff answered my question 👍

**Comment by richardwaite** [comment]
For anyone trying to get this working now, you can open the VM in the Fusion interface and run the copy command manually. This requires you to use the /var/lib/boot2docker/userdata.tar because by the time you can access the shell it appears it's already been moved.

The full command would then be:

`tar xvf /var/lib/boot2docker/userdata.tar -C /home/docker > /var/log/userdata.log 2>&1 && chown -R docker:staff /home/docker`
