### ISSUE TITLE
openstack: Remove machine locally if api returns 404

### ISSUE THREAD

**Issue by davidarcher** [docker/machine#4362]
When using docker-machine with the GitLab CI runner, it is unable to remove the local references to machines that have been removed manually on the cloud instance.

```
time="2018-01-11T20:52:23-05:00" level=error msg="Error removing host \"runner-c75c2f88-1515719299-dea1b3b5\": Expected HTTP response code [202 204] when accessing [DELETE https://openstack.example.org:8774/v2.1/servers/219e7951-a5fa-4a5d-ad5c-3f754f5ca3f1], but got 404 instead" name=runner-c75c2f88-1515719299-dea1b3b5 operation=remove 

time="2018-01-11T20:52:23-05:00" level=error msg="{\"itemNotFound\": {\"message\": \"Instance 219e7951-a5fa-4a5d-ad5c-3f754f5ca3f1 could not be found.\", \"code\": 404}}" name=runner-c75c2f88-1515719299-dea1b3b5 operation=remove 
```

We fixed similar for [EC2](https://github.com/docker/machine/issues/4112) and [GCE](https://github.com/docker/machine/issues/4251) already by just warning and proceeding when the cloud provider API returns a 404. We should do the same for openstack.

**Comment by jshumaker** [comment]
I'm still seeing this issue with 0.14.0 and 0.15.0.  I have to add a -f to force the removal, it doesn't treat the 404 as a warning.

If I run docker-machine ls, it shows the status as:

`runner-2706434e-gitlab-runner-1538716539-cac9712b   -    openstack   Error             Unknown   Expected HTTP response code [200 203] when accessing [GET https://openstack02.jpg.com:8774/v2.1/d5c2ec3a754e48f48e06737a96a05e25/servers/], but got 404 instead
{"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}`

When I try to run a removal I get:

`About to remove runner-2706434e-gitlab-runner-1538716539-cac9712b
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): y
(runner-2706434e-gitlab-runner-1538716539-cac9712b) Deleting OpenStack instance...
(runner-2706434e-gitlab-runner-1538716539-cac9712b) Remote instance does not exist, proceeding with removing local reference
Error removing host "runner-2706434e-gitlab-runner-1538716539-cac9712b": Expected HTTP response code [202 204] when accessing [DELETE https://openstack02.jpg.com:8774/v2.1/d5c2ec3a754e48f48e06737a96a05e25/os-keypairs/], but got 404 instead
{"message": "The resource could not be found.<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"}`

I have to use -f or it doesn't remove. Which causes a problem with gitlab-runner because it never forcefully tries to remove them, so these invalid entries can accumulate over time.
