### ISSUE TITLE
Duplicate: Hyper-V PowerShell Module is not available

### ISSUE THREAD

**Issue by SpamhaterAlex** [docker/machine#4468]
Hi, 

I tried to make the instructions of this docs: 
https://docs.docker.com/machine/drivers/hyper-v/#4-create-the-nodes-with-docker-machine-and-the-microsoft-hyper-v-driver 

But, when I start the powershell and write the command: 
`docker-machine create -d hyperv --hyperv-virtual-switch "Primary Virtual Switch" manager1 `

I get this error: 
`Hyper-V PowerShell Module is not available`

This issue is a duplicate of:
https://github.com/docker/machine/issues/4424 

I tried to understand, how to fix it, but dont get it.. 

Are there some documentations, or instructions to solve this problem? 
As I see, many have the same problem with it? 

I would be happy, if somebody can help me out :) 

Thanks

**Comment by stormxing** [comment]
+1

**Comment by Adiqq** [comment]
This issue should be fixed by new release, but I can't comprehend why 0.14.1 is not still there? It basically means, that you can't easily run docker machine with hyperv on windows for 2 months now!
Fix exists, but was not released and that's very bad user experience for new potential users.

@dgageot @jeanlaurent @shin-

**Comment by dgageot** [comment]
I'm sorry I can't do the release. @jeanlaurent or @shin- from Docker can decide when to do a release.
