### ISSUE TITLE
Proposal: Logging changes

### ISSUE THREAD

**Issue by sthulb** [docker/machine#463]
We should:
1. Make all logging go to stderr except for info level logs.
2. Figure out if this would be useful for @sirupsen's logrus package, if so, push it there.

Remove the prefix from INFO level logs so we no longer see "INFO[0000]" or just use stdout + `fmt.Print*`

**Comment by Sirupsen** [comment]
To change to `stderr` you can just do `logrus.SetOutput(os.Stderr)`.

In regards to removing the prefix, we could make that [an option on the `text_formatter`])[https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L35].

**Comment by ehazlett** [comment]
@Sirupsen thanks.  can you currently split out `Stdout` and `Stderr`?  It didn't look like it.

+1 for the custom formatting

**Comment by Sirupsen** [comment]
Ooh, I read it too fast. No, you currently can't split `Stdout` and `Stderr`. I don't like that behaviour from loggers.

**Comment by nathanleclaire** [comment]
We _really_ should split the project into client/daemon first before doing this.  Otherwise we will just be setting ourselves up for a lot of pain down the line when we do so.  Think about it.  Output on daemon side should basically always use logrus and should probably always write to STDOUT as well.  Output on client side should pretty much never use logrus and will sometimes write to STDOUT (e.g. `ls` output), sometimes to STDERR (e.g. something failed during create).  If we go implementing a mixed solution at this point we'll have to fix it all later.

**Comment by ehazlett** [comment]
@nathanleclaire +1

**Comment by Sirupsen** [comment]
Well articulated!

**Comment by sthulb** [comment]
@nathanleclaire agreed. 

Perhaps for 0.2.0 we can move to server/client to fix this.

**Comment by ehazlett** [comment]
I'm all for this :)

**Comment by ehazlett** [comment]
We should handle this (standardized logging) as part of the refactor in #553.

**Comment by crunchywelch** [comment]
@nathanleclaire @ehazlett  hopefully not hijacking this thread too badly, but I'm writing a logentries hook for logrus, and integrating it into a special branch of docker machine, would there be any interest in spending some time finding a way to provide the ability to set the logging backend using the logrus hook functionality in machine? Let me know if I should make a new proposal issue for this if there is interest and I can keep the conversation going...
