### ISSUE TITLE
docker-machine output kind of funky on Cygwin on Windows

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#501]
I like Cygwin for Windows and haven't tried with Msysgit but the logging output looks pretty funky on Cygwin on Windows.

![windows_machine_logs](https://cloud.githubusercontent.com/assets/1476820/6093694/c33d746e-aebe-11e4-9cdd-933333865cf1.jpg)

Just marking it down for future reference; it's one reason why I'm in favor of not doing daemon-style logs on the client side.

**Comment by ehazlett** [comment]
I agree.  This looks better than default msysgit (it shows escape codes).

**Comment by ehazlett** [comment]
We also need to get an "official" supported way to run on all platforms.  OS X / Linux are pretty straight forward.  For Windows, we need to at least document out the recommended way and tools needed.  Right now that is msysgit but I'm probably the last one to recommend.  I chose msysgit because it seemed to be the lowest barrier to entry from the user side.

I think once we fix client logging this won't be as big of an issue.

**Comment by SvenDowideit** [comment]
main thing with msysgit, is that we've used it with boot2docker for the last year. One thing we wanted to try, is to use a zero-install version of the tools and plonk them into the b2d/machine dir to avoid conflicts with other installed tools.

getting everything so it works in those unix shells and cmd.exe and powershell is a bit of a horror though.

**Comment by ehazlett** [comment]
yeah i agree.  i'm all for using something else if we can get them to play
nice.

**Comment by nathanleclaire** [comment]
This is done

**Comment by znmeb** [comment]
FWIW I've had pretty good luck on Windows boxes with MSys from the MSysGit installer when I allow the installer to add the *nix utilities to the Windows PATH. The terminal windows have the usual goodies - bash, readline, tar, grep, etc., and IIRC an ancient Perl as well. And you still have the Windows command-window copy and paste with the mouse.

If at all possible I'd avoid CygWin - it does bizarre things to the Windows permission bits to get a Linux-like environment. If you must use CygWin, make a separate Windows partition for it rather than letting it touch your "C" drive.

**Comment by nathanleclaire** [comment]
@znmeb Yep, our official install path (at least for now) on Windows is to use msysgit- this issue was more about the formatting of the log statements being hard to read.
