### ISSUE TITLE
[AmazonEC2 driver] -- stuck with "Waiting for SSH on..." when creating new instance

### ISSUE THREAD

**Issue by andrea-spoldi** [docker/machine#581]
Hi, 
just starting using machine, noticed that it automatically assigns a public IP address to the newly created instance in VPC, then waits for SSH connection to be up as signal for instance creation complete .

Which is great, unless the subnet you are creating the instance in is a private one and not a public one. 
In this case the check on port 22 on the IP address fails for missing NAT between the IP address, the route instance needed for VPC's private instances to be accessed, and the instance itself.

A workaround would be using a VPN from your client to VPC, but you should then be able to pass also --ip-address option to machine, like this : 

machine -D create -d amazonec2 --amazonec2-access-key="..." --amazonec2-secret-key="..." --amazonec2-subnet-id="subnet-myprivatesubnetid" --amazonec2-vpc-id="vpc-myVPC" --ip-address="my.private.ip.address" new-private-intance-name 

Thank you

A

**Comment by sthulb** [comment]
Honestly, there are lots of useless like this one we haven't thought of.

I'm not sure how we would even start to allow for them without 100s of flags for the driver. :/ 

@ehazlett perhaps something we should think about.

**Comment by andrea-spoldi** [comment]
thanks for reply @sthulb 
I'm sure there are 100s and 100s of them, I just pointed out this particular one 'cause having an AWS VPC with public and private subnets is a very common scenario, but machine won't work in a such environment at all (at the moment ;) )

**Comment by md5** [comment]
It seems like having a --no-public-ip option and requiring the user to be
connected to their VPN should be enough.

**Comment by andrea-spoldi** [comment]
@md5 for sure yes

**Comment by ehazlett** [comment]
@andrea-spoldi we would still need some form of specifying which IP address the instance has, correct?

**Comment by andrea-spoldi** [comment]
@ehazlett well, that would be cool but not necessary mandatory; within VPC subnet (private) IP address are managed via DHCP; upon instance creation you might specify an address, otherwise a free random one is used from the subnet, so probably the IP can be retrieved via API after the instance is created and while it's being set up.

**Comment by ehazlett** [comment]
ah ok thanks

**Comment by md5** [comment]
I'll just add that it may be possible to programmatically detect whether the VPC that an instance is being attached to is public or private by looking at its route table using the EC2 API (`DescribeRouteTables` specifically). That may be preferable to a hokey `--no-public-ip` option if it can be done.

**Comment by andrea-spoldi** [comment]
@md5 actually I think the VPC itself is private/public agnostic, is the subnet itself which might be private or public on route-table basis; so you should first lookup the provided subnet-id for its route-table, and then check the routing table in order to understand if it uses a VPC internet-gw (hence is should be a public subnet) or another instance interface, which (the instance) act as software router, so the subnet is a private one with no direct access to the Internet.

It would mean, I think, some more code lines against adding some more argument, which would raise complexity on user side, but (maybe) less code.

I'd be happy with whichever solution anyway :)

**Comment by md5** [comment]
@andrea-spoldi Indeed. Thanks for clarifying.

**Comment by TMaddox** [comment]
This is also a problem when behind firewalls and proxying. The step for checking for SSH doesn't appear to honor proxy configs.

**Comment by md5** [comment]
@TMaddox `docker-machine` is SSH'ing by IP address as I understand it, so you'd have to have either a global `ProxyCommand` or something like `Host 10.*`.

**Comment by TMaddox** [comment]
Sorry, I may be missing something. During the create process when it's waiting for the SSH server to come up, It looks like it's just doing a TCP ping to that port, not actually SSH'ing:

https://github.com/docker/machine/blob/4f5de31d3f623d5367a0dd76bba202b467852525/drivers/amazonec2/amazonec2.go#L281-L283

https://github.com/docker/machine/blob/master/ssh/ssh.go#L64-L76

I have the proxy configured in my ~/.ssh/config. Is that what you're suggesting or something else? When this waitForTCP was replaced with an SSH call that just executed 'true' at that step to check for the SSH server being available, the build went through fine and it honored the proxy configuration.

I have only tried with the Rackspace driver, but just noticed similar behavior in terms of the create hanging at this step as I believe is what's described in this issue, so wanted to mention here rather than opening an issue against that driver as I suspect it may be a problem in multiple drivers. :)

**Comment by md5** [comment]
@TMaddox nope, looks like I was missing something :+1:

**Comment by ehazlett** [comment]
So just to clarify, this is because the instance is private and it's trying to connect to the private IP?  I like @md5 suggestion of the `--no-public-ip` option.  Are we safe to ensure the user has a VPN connected?  I think that would be OK.

**Comment by md5** [comment]
@ehazlett I think it's actually that the instance is on a subnet that is behind a NAT and thus not routable from the outside. The instance is getting a public IP, but it isn't able to use it.

**Comment by ehazlett** [comment]
ah ok thx

**Comment by DKientz** [comment]
It is not pull request ready :-(, but this solved the problem for me so that I can at least create my swarm
https://github.com/DKientz/machine/commit/7933e5d7238df4902c18ca8bae32f94b3f09d64b
* You can use the flag amazonec2-use-private-ip-address=true
* Fixes a bug that tried to duplicate port 3367 on the security group
* It uses docker.io instead of lxc-docker during apt-get

**Comment by include** [comment]
one more guy hitting on this problem. :/ I have many vpcs in many aws accounts. all of them share this pub/priv nat setup. I would love to run swarm here.

**Comment by andrea-spoldi** [comment]
can't quite understand if this has been addressed somehow with recent machine 0.2 release...
Release notes state : 

Support for using Private IPs in VPC

and if I try to create a new machine : 

DEBU[0025] created instance ID i-f8fdfb2f, IP address 52.1.252.193, Private IP address 10.0.1.173 

...but it still tries to check for port 22 on the public IP, so it fails again...

missing something ?

**Comment by ehazlett** [comment]
@andrea-spoldi currently the check is "automatic".  If the instance does not get a public IP (i.e. you don't have that enabled in the subnet) then it will use the private.  Otherwise, it uses the public.  

Also note, you must have a connection to the VPC via VPN (we do not handle tunneling etc -- it's assumed you can connect to the private address space).

**Comment by andrea-spoldi** [comment]
Hi @ehazlett thanks for replying...
Sorry but I think I do not understand what you mean for "automatic" 

this is what I use : 

docker-machine -D create -d amazonec2 --amazonec2-access-key="mykey" --amazonec2-secret-key="myscret" --amazonec2-subnet-id="subnet-MY-PRIVATE-SUBNET" --amazonec2-vpc-id="vpc-MYVPC" test-machine2

sorry for using caps 

I'm on VPN, the new instance receives both a public ip address and a private one, but the check for port 22 still happens on public IP only...

I'm sure I'm failing somewhere but can't see where

A

**Comment by ehazlett** [comment]
@andrea-spoldi my apologies -- i thought we had this configurable.  It looks like we forcibly specify the configuration of  a public address (https://github.com/docker/machine/blob/master/drivers/amazonec2/amz/ec2.go#L189) -- I thought we deferred to whatever the "Auto-Assign Public IP" setting of the subnet group.  Would you mind opening an issue to add that functionality?

**Comment by andrea-spoldi** [comment]
Hi @ehazlett , done .

**Comment by ehazlett** [comment]
@andrea-spoldi thanks!  i'm going to close this on and continue with that one.  We will get this for the 0.3.0.

**Comment by Aniket-Singla** [comment]
For my case , issue was that my IP address was not added to allowed ssh hosts in the security group used by that virtual machine. I added my machine to allowed hosts and it worked like charm.
