### ISSUE TITLE
Allow for nested machines

### ISSUE THREAD

**Issue by michaelsbradleyjr** [docker/machine#636]
**Use Case**
I've found it useful to provision a Digital Ocean server with ample resources using `docker-machine` (been an avid user since `0.0.2`!). Then I use `docker-compose` (previously `fig`) to create "inception" docker-in-docker contexts, to which I deploy my stacks. This provides a nice level of logical separation and I find it preferable to provisioning several smaller Digital Ocean servers (with `docker-machine`).

**Feature Request**
It would be wonderful if `docker-machine` had the ability to provision "nested" machines within an existing machine. Such nested machines would not need to run under full virtualization but could instead use a "docker-in-docker" approach. From the perspective of the `docker-machine` cli, working with those nested machines would be no different than working with top-level machines.

**Comment by dgageot** [comment]
Hi @michaelsbradleyjr, thank you very much for the time you spent writing this proposal. We can see the value it would bring to a few users. However, because we must concentrate our energy on what's used by the most, we are going to close this ticket with the status "out of scope".
Once again, let us thank you for using docker-machine and trying to improve it.

**Comment by michaelsbradleyjr** [comment]
@dgageot so, if a mac is my principal development machine, is there a recommended way to setup up virtual Windows hosts, in a command-line oriented and automate-able manner, on which to run the Docker daemon?
