### ISSUE TITLE
[openstack] SSH password

### ISSUE THREAD

**Issue by timbordemann** [docker/machine#656]
When creating a new docker machine using the openstack driver, I am asked for a ssh password:

    DEBU[0081] Waiting for the SSH server to be started...   IP=x.x.x.x MachineId=0d893949-aae6-4777-aa7e-378216f3c472
    DEBU[0098] generating server cert: /Users/user/.docker/machine/machines/test103/server.pem ca-key=/Users/user/.docker/machine/certs/ca.pem private-key=/Users/user/.docker/machine/certs/ca-key.pem org=test103
    DEBU[0100] Stopping Docker...
    DEBU[0100] Command: %s[sudo sh -c 'sudo service docker stop']  MachineId=0d893949-aae6-4777-aa7e-378216f3c472
    DEBU[0100] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /Users/user/.docker/machine/machines/test103/id_rsa centos@x.x.x.x sudo sh -c 'sudo service docker stop'
    centos@x.x.x.x's password:

When I try to connect to that machine manually, I am not asked for a password though. This seems to be the same issue as described in #480 .
Is there a way to force docker-machine to wait for a specific period before connecting to the machine?

**Comment by nathanleclaire** [comment]
I seem to recall having an issue similar to this the other day.  Do you get the same result if you run the command without debug @timbordemann ?

**Comment by ggiamarchi** [comment]
This is a common issue depending on how the cloud image has been built. Basically, some race conditions can cause two annoying situations :

1. When the SSH server is up and listening but the user we use to log in is not yet created
2. When the SSH server is up and listening and the user exists but the public key is not yet deployed

I had to deal with exactly the same problem on the [Vagrant OpenStack Provider](https://github.com/ggiamarchi/vagrant-openstack-provider) and i think the only solution to cover both those situations are to try to establish a real SSH connection rather than only check that the tcp port is open. Furthermore, we have to add the option `-o PasswordAuthentication=no` to avoid prompting password and fail instead.

Also, this issue is probably not really OpenStack specific, it could happen on any machine.

I've implemented a bugfix here https://github.com/docker/machine/pull/665.

@timbordemann @nathanleclaire can you test it ?

**Comment by timbordemann** [comment]
@ggiamarchi Yes, i confirm your solution solves the problem, that docker-machine tries to connect to the host before the keys are set up.

**Comment by ehazlett** [comment]
@ggiamarchi @timbordemann can we close this or is there more action needed?

**Comment by ggiamarchi** [comment]
@ehazlett I'm not sure what you mean by "close this". This is the PR #665 that fix the bug.

**Comment by ehazlett** [comment]
@ggiamarchi ah ok sorry!

**Comment by hairyhenderson** [comment]
I'm guessing this can probably be closed now, based on the status of #665?

**Comment by ehazlett** [comment]
@hairyhenderson thx!  closing as new ssh detection is in place.  please feel free to re-open if the issue continues.
