### ISSUE TITLE
Proposal: Mosh as an option in addition to SSH

### ISSUE THREAD

**Issue by UserTaken** [docker/machine#704]
Mosh has been a lifesaver when on an unstable and/or high latency connection. Including Mosh when provisioning should not take a noticeably longer time as the package is less than 1MB to download. In conjunction, perhaps add an **-m** argument to **docker-machine ssh** to use Mosh instead of SSH. That will be much more convenient than what I've been currently doing which is :

```
ssh -i ~/.docker/machine/machines/test/id_rsa $(docker-machine ip) apt-get install mosh -y
mosh --ssh "ssh -i ~/.docker/machine/machines/test/id_rsa" $(docker-machine ip)
```

https://mosh.mit.edu/

**Comment by sthulb** [comment]
This should probably be a plugin rather than core functionality.

**Comment by nathanleclaire** [comment]
@UserTaken I'm not sure if you're aware but for the first command you could use:

```console
$ docker-machine ssh moshbox -- apt-get install -y mosh
```

For the second one, I've been thinking that for this and other things a `docker-machine ssh-key` command (which would print the path to the key and do other operations related to SSH key management) would be useful - that would at least make the command a little less hairy since you wouldn't have to manually look up the path to the key.  It would be something more like:

```console
$ mosh --ssh "ssh -i $(docker-machine ssh-key moshbox)" $(docker-machine ip)
```

(this would at least let you make a generic shell function for convenience)

I definitely want to make this feature available to people, since I have an interest in `mosh` as well, but using well-integrated and decoupled components rather than hardcoding `mosh` into what we have already.  So stay tuned.

**Comment by UserTaken** [comment]
@nathanleclaire

Thanks for the first tip. Having an **ssh-key** command would be helpful although taking in your suggestion, this one liner to install Mosh then Mosh into the current active machine also works.

```
docker-machine ssh $(docker-machine ls | grep "*" | awk '{print $1}') -- which mosh &>/dev/null || docker-machine ssh $(docker-machine ls | grep "*" | awk '{print $1}') -- apt-get install -y mosh && mosh --ssh "ssh -i ~/.docker/machine/machines/$(docker-machine ls | grep "*" | awk '{print $1}')/id_rsa" $(docker-machine ip)
```

**Comment by nathanleclaire** [comment]
Cool @UserTaken !

**Comment by nathanleclaire** [comment]
@UserTaken One more tip :)

You can use `docker-machine active` to get the name of the active host.  So, no need for the little awk pipeline if I understand the command correctly.

It could look like this instead:

```console
$ docker-machine ssh $(docker-machine active) -- which mosh &>/dev/null || \
    docker-machine ssh $(docker-machine active) -- sudo apt-get install -y mosh && \
    mosh --ssh "ssh -i ~/.docker/machine/machines/$(docker-machine active)/id_rsa" $(docker-machine ip)
```

**Comment by thaJeztah** [comment]
@nathanleclaire perhaps that's worthy to add in a `contrib` in the repository?

**Comment by UserTaken** [comment]
@nathanleclaire

I forgot `docker-machine active` without any arguments prints the current active machine so thanks for reminding me. The first SSH command does not contain any arguments so the flag parsing terminator is not needed. Most of the cloud drivers default to root for SSH so when using Mosh as a local non root account, `root@$(docker-machine ip)` need to be specified.

```
$ docker-machine ssh $(docker-machine active) which mosh &>/dev/null || \
	docker-machine ssh $(docker-machine active) -- sudo apt-get install mosh -y && \
	mosh --ssh "ssh -i ~/.docker/machine/machines/$(docker-machine active)/id_rsa" root@$(docker-machine ip)
```

**Comment by nathanleclaire** [comment]
:+1: Fun stuff.
