### ISSUE TITLE
Idea: call the thing that Machine creates "hosts"

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#727]
"Use Machine to create a machine."

[This is kind of my fault, sorry.](https://github.com/docker/machine/pull/84) In documentation and so on, I find it very confusing trying to explain this sort of thing. The only distinction we make between Machine and a machine is whether it's a proper noun or not.

How about we call the thing that Machine creates a "host"? That's a word we've been using for ages with Docker, and we often use that word in Machine-land too.

"Use Machine to create a host."

**Comment by bfirsh** [comment]
(I'm calling this an "idea" because I don't have any strong opinions... something less forceful than a proposal. ;)

**Comment by hairyhenderson** [comment]
Would this be just a documentation change, or would also change directory name(s) and source code?

Personally I prefer the term "host" too

**Comment by ehazlett** [comment]
I personally like "instance" but I'm not very strong on it either.

**Comment by sthulb** [comment]
Host is fine.

**Comment by nathanleclaire** [comment]
Heh.  I'm -1 on changing on terminology inside the code or in our general approach to explaining things at this point (more important things to do IMO), but an FAQ / glossary in the docs (as well as a discussion in a style guide if we evolve one) would probably go a long way.

i.e.:

### Terms

**Docker Machine** - The open source project and binary which is used to create and control new compute instances which run Docker.
**Machine** - The created instance which is running Docker.  This could be a local virtual machine on a laptop or a virtual machine running in the cloud.  This is sometimes referred to as a "host", an "instance", or a "daemon" (referencing the Docker daemon which is running on them).
**Provisioning** - The step in creating a machine which installs Docker, properly configures the machine so that the Docker client can connect to it, and bootstraps the specification outlined in the provided `cloud-init` file

etc.

**Comment by ehazlett** [comment]
Cool.  Hosts it is.  @bfirsh do you want to open smaller issues with where this needs updated?  I imagine at least the docs and readme but perhaps more.

**Comment by thaJeztah** [comment]
Perhaps late to the party (catching up); when used in combination with Swarm, a `host` created by Machine will be called a `node` in swarm terminologies; will that be confusing for users? Does it need some explanation what the difference between a "node" and a "host" is?

**Comment by bfirsh** [comment]
I am purely talking about the terminology we use to communicate through docs and the UI. That said, it probably makes sense for us to use the same terminology in the code too. (Which conveniently happens to be "host". ;)

We've got `~/.docker/machine/machines` though, which is a bit annoying. (Sorry @ehazlett, my fault again!)

**Comment by bfirsh** [comment]
@thaJeztah Yes, I think it is a bit confusing that we use both "host" and "node". Swarm could clarify that a node is a host which is part of a Swarm, but it would be really good if we could agree on a single term. /cc @aluzzardi @vieux

**Comment by bfirsh** [comment]
@ehazlett ["Host" is a term that we already widely use.](https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Adocker.com%20host) Open to suggestions though... I think "instance" could be too cloud specific.

**Comment by bfirsh** [comment]
"Engine" could be another word we could use, if we wanted to conflate the host and the daemon running inside it.

**Comment by sthulb** [comment]
@bfirsh I had the same thought... Docker uses the term host in most places.

**Comment by ehazlett** [comment]
@bfirsh host is fine with me.

**Comment by thaJeztah** [comment]
I'm +1 on host ("engine" and "instance" are only confusing I think) with the added note that "node" (in context of swarm) needs a short explanation in the docs.

**Comment by nathanleclaire** [comment]
I think this issue has not really gone anywhere and I personally and fine with the current naming.
