### ISSUE TITLE
Validate instance creation for DigitalOcean using driver flags

### ISSUE THREAD

**Issue by crosbymichael** [docker/machine#838]
**Problem**

Test the flags for DigitalOcean

**Solution**

Validate instance creation in DigitalOcean using various driver flags

There are several flags available for each driver.  Test each flag to ensure it does the intended behavior.

For example,

`docker-machine create -d digitalocean --digitalocean-size "512mb" test-do`

This should create a machine in do with 512 MB of memory.

**Comment by thaJeztah** [comment]
@crosbymichael is this "manually" testing, or an automated test?

**Comment by jeremy646** [comment]
#dibs

**Comment by jeremy646** [comment]
Just needed to add the --digitalocean-access-token flag with my DO token for a successful droplet creation - ny3 and ubuntu 14 are default. Tested additionally with the --digitalocean-image flag and the --digitalocean-region flag.

The image flag worked for ubuntu 14, debian 7, 

Fedora 21 could not install docker. Coreos and centos showed invalid image errors (not surprising for centos)

The region flag is tricky because some of these regions are just straight up unavailable or won't support user data in combination with certain distros. So, you'd need to have some inside info on which situations play nice beforehand.

Sample successful command:

docker-machine create -d digitalocean --digitalocean-image "debian-7-0-x64" --digitalocean-region "nyc3" --digitalocean-access-token MY_TOKEN --digitalocean-size "512mb" test-do9

**Comment by janeczku** [comment]
> The region flag is tricky because some of these regions are just straight up unavailable

Yes that's a problem. The user or application deploying via machine does not know about current availability of zones or the available instance sizes in a particular zone.
A solution would be to expose this information via the drivers, since most provider APIs include this information anyway.
Then the user could have machine list the available zones and instance sizes for a particular provider.

**Comment by nathanleclaire** [comment]
My opinion is that this is out of scope for Machine.  The user must set the correct parameters, and we can try to help, but we have to draw the line somewhere.
