### ISSUE TITLE
Validate instance creation for VMware vCloud using driver flags

### ISSUE THREAD

**Issue by crosbymichael** [docker/machine#845]
**Problem**

Test the flags for VMware vCloud Air

**Solution**

Validate instance creation using various flags for VMware vCloud Air

There are several flags available for each driver.  Test each flag to ensure it does the intended behavior.

For example,

`docker-machine create -d vmwarevcloudair --vmwarevcloudair-memory-size "4096" test-vcloudair`

This should create a machine in vcloudair with 4096 MB of memory.

**Comment by sophokles73** [comment]
Testing on
```
kai@vader:~$ docker-machine -v
docker-machine version 0.3.0-dev (fec8b4a)
```

Mandatory flags used in order to connect to vCloud Air:

* `--vmwarevcloudair-username`
* `--vmwarevcloudair-password`
* `--vmwarevcloudair-vdcid`
* `--vmwarevcloudair-orgvdcnetwork`
* `--vmwarevcloudair-publicip`

## Flags to test

* `--vmwarevcloudair-cpu-count`

## :red_circle: [FAIL] Can create a VMware vCloud Air machine with 2 CPUs

Console output

```
kai@vader:~$ docker-machine create -d vmwarevcloudair --vmwarevcloudair-username XXXXX
--vmwarevcloudair-password XXXXXX --vmwarevcloudair-cpu-count 1
--vmwarevcloudair-vdcid Mxxxxxx-xxxxx --vmwarevcloudair-orgvdcnetwork Docker-Infrastructure
--vmwarevcloudair-publicip xxx.xxx.xxx.xxx docker-node
Connecting to vCloud Air...
Creating a new vApp: docker-node...
Waiting for the VM to power on and run the customization script...
Creating NAT and Firewall Rules on Mxxxxxxxx-xxxxx...
Error creating machine: error reconfiguring Edge Gateway: API Error: 400: The parameter Algorithm is not supported in member service port.
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

vAPP and VM are created and started in vCloud Air but the firewall and NATing rules are not created (as the error message on the console also indicates).
