### ISSUE TITLE
Do not save new host unless driver.create() succeeds

### ISSUE THREAD

**Issue by janeczku** [docker/machine#972]
When driver.create() fails with error, the host is saved to the store anyway. As a result while the user is shown a `Error creating machine` message, subsequent `docker machine ls` will still display the host even though it was never created in the first place.

Is there a reason, why SaveConfig() is called *before* actually creating the host?
https://github.com/docker/machine/blob/1b81ddeb900e81381ffc29d23d289695b51fa2f0/libmachine/machine.go#L55-L57

**Comment by ehazlett** [comment]
Yes, this way if there is a momentary blip during provisioning of a cloud instance, we have the credentials, etc so we can do a `docker-machine rm`.

**Comment by janeczku** [comment]
@ehazlett  When you say "provisioning", do you refer to the provisioning portion of the code (which comes after driver.create()) or to creating an instance in the cloud?

**Comment by ehazlett** [comment]
Sorry, I mean the process of creating the instance.  For example, if the EC2 API has a fail or the instance has an issue starting, then this gives us the ability to fail with an error and still have the persisted credentials so the user can then issue the `rm` command.  Otherwise, the user must login to whatever console or separate tool to remove the instance.

**Comment by janeczku** [comment]
If, like in your example, the EC2 API has a fail, isn't leaving the host in the store not helping the user at all since without having received the instanceID from the API a `rm` command will always fail?
  
Why i think the current behavior is not ideal:
  
1. Machine host store should be in-sync with what is actually deployed by machine in the cloud.
By storing a (likely) failed deployment this is not true anymore.
2. Having to `rm` a host (as in destroy the instance in the cloud) after the creation of that very host failed in the first place seems counter-intuitive from a users perspective.
3. Why expect the user to clean up the host store from stale entries (failed deployments), if those might be dealt with programmatically?

Now, there are several scenarios i can think of in which driver.create() would fail:   
    
**Scenario 1 - Very likely**   
Instance was not created - API endpoint failure   
**Scenario 2 - Very likely**   
Instance was not created - API endpoint OK (no free instances available in region, account issues, etc)
**Scenario 3 - Likely**       
Instance was created, but has an issue starting up    
**Scenario 4 - Not so likely**    
Instance was created, but API responses are faulty    
    
Why not try to first deal with those scenarios programmatically and only in case of a persistent API failure then fallback to user required action?
E.g. something like this:  
   
1.  If driver.create() fails => try driver.delete() => if success then delete host from store
2. The drivers delete() method should only return with error in case of API errors. If the request was successful but instance was not found it should return success (as already implemented by the digitalocean driver https://github.com/docker/machine/blob/1b81ddeb900e81381ffc29d23d289695b51fa2f0/drivers/digitalocean/digitalocean.go#L313-L314) 

What do you think @ehazlett ?

**Comment by nathanleclaire** [comment]
Hi @janeczku,

I applaud the sentiment to improve the user experience, but it's been my experience from working on machine that the problem here is much deeper than shuffling around where and when the config file gets saved.  I filed a very similar issue here: https://github.com/docker/machine/issues/119 a while back and we played around with various solutions, including auto-cleanup, which we eventually reverted. I have a strong feeling that our current approach is getting close to a "happy place" for the existing machine model  and something we should stick with until we re-think and re-implement some pretty fundamental things about machine related to host discovery, failure tolerance, and a few other areas.  Remember that this is a trickier distributed systems problem than it initially appears to be.

Here are some things to consider in that regard.

Perhaps most importantly: if you are unable to create a host reliably, then you are equally likely to have a bad time removing it reliably.  Let's imagine that `docker-machine` doesn't have any bugs in the code (hey, a guy can dream).  If that is the case, this mostly leaves three possible sources of failure in a create as I see it: 

1. Issues with the provider (e.g. their API is down or they have frozen actions), or : 
2. Issues with the network (e.g. they're on the Docker office WiFi)
3. Issues with provisioning (e.g. the machine was created just fine, but our package manager archives are having an outage)

In the first two cases, it is particularly perilous to assume that we can do a remove safely (since one operation already failed).  And if `Remove` fails as well, then the user experience of cleaning up failed host creates becomes a lot more inconsistent.  It makes it a lot harder to predict when a host will and will not be removed.

It is _always_ worse to not know about a failure than to assume that everything went fine when it did not, especially when :moneybag: is on the line.  So, to that extent, we let the users know that there was a failure and leave it to them to clean it up how they want to.  After all, an outage right now could be fixed in five minutes or so.  Failure will happen a lot, especially as the number of machines + users increases, so IMO it's probably better to equip users with the tools to handle it than to try and hide it.

I definitely think that the user experience around running `docker-machine ls` and other commands when there has been / is an issue with the machines in question could be vastly improved, so I'm highly open to suggestions and discussion there if you have ideas.

In the third case I listed above (provisioning failed), even though an `error` would be returned by the `Create` call (ideally it should time out instead of just hanging), we may not even _want_ to remove the host, but rather re-provision it (this is not implemented today, but it has been a very common case of failure lately and there's no reason to blow away the whole host just because provisioning went weirdly).

All of this is largely why we are working to make the window between "create the machine" and "save the relevant identifier/token" as small as possible.  Instances that can be identified can be removed reliably.  This is still a work in progress, so the more the merrier in terms of spotting remaining issues which cause specific `Create` calls to take longer than they should (e.g. some drivers still do things like check if they are up which now have been centralized).  This also could perhaps be done better - it's why I bring up discovery above - by having some kind of fall back.
