### ISSUE TITLE
Proposal: Support configuration of created Docker Engines from Machine CLI

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#974]
### Abstract

This proposal outlines a method by which users would be able to more flexibly configure Docker daemons created by Docker Machine.  It is a more fleshed out version of https://github.com/docker/machine/issues/902 .

### Setup

Currently we support the "bare minimum" required configuration of a Docker daemon in created instances.  This works great for things like TLS configuration where the details are generally abstracted away from the user and the user does not care about them.  However, there are several things users might want to do with their created instances, e.g. use an insecure private registry, which require fiddling with Docker daemon flags but are not currently supported by Docker Machine.  This proposal is to add a way to set them.

### Implementation

This proposal would add extra flags to `docker-machine create`.  In general, the pattern that I would like to follow is `--engine-docker-flag`.  So, `--insecure-registry` would become `--engine-insecure-registry` and so on.  The args passed to `docker-machine` would then directly be translated into daemon arguments on the remote machine.

Proposed flags to support:

- `--engine-label` : Label Docker Engines (useful for clustering)
- `--engine-graph`: Configure where graph is located (usually `/var/lib/docker`)
- `--engine-storage-driver`: Configure AUFS, BTRFS, overlayfs etc.
- `--engine-insecure-registry`: Specify a registry to use insecurely (very annoying to add manually)
- `--engine-registry-mirror`: Specify a registry mirror to use

We would use these to get a base structure for this and gradually expand support to more configuration options.

The structure to implement this is pretty close already.  Provisioning is done based on OS and each provisioner (there are only two for now) will simply have to create a template for the "daemon configuration file" relevant to that distro which will get filled in based on the internal `EngineOptions` struct from `libmachine`.

### Concerns

- There is an explosive amount of `docker-machine create` flags and this will make the problem worse.  In the future (relatively soon) we want to move to defining machine configuration in a file (https://github.com/docker/machine/issues/773) to mitigate this problem.
- Where does the line get drawn?  That is, when we start discussing allowing the configuration of things like storage drivers, where does Docker Machine's responsibilities lie?  Will Machine install dependencies such as BTRFS if they are needed or is that left to the user?  I would argue that we should keep things simple for now (just read in config from the CLI and spit out the proper file on the remote), but leave the conversation around automatically handling these things open, as it is likely that automatically setting some things such as this up for the user could be pretty valuable.
- How do we handle multi-args, e.g. specifying multiple `--insecure-registry`, or `-H` options etc.?  (I think `codegangsta/cli` supports this via e.g. `cli.StringSliceFlag`)

cc @sthulb @bfirsh @amylindburg @ggiamarchi @hairyhenderson for thoughts / concerns / comments

**Comment by nathanleclaire** [comment]
oh and cc @ehazlett of course :+1:

**Comment by hairyhenderson** [comment]
:+1: I like this, and I like the possibilities that this adds.

I'm also concerned about the growing plethora of `create` options. I think it's been suggested a few times before, but there is the option of turning `create -d drivername` into `create drivername` (i.e. making the driver a subcommand instead of a flag. There's some discussion of that in #901. I _think_ that would make the flags business a little easier to manage, but maybe at the expense of a weird UI.

_However_, you're _only_ talking about 5 new options, and given that there are already >100, what's 5 more? ;)

Re: scope - Keeping it simple is a good start ;) Part of the challenge is Machine needs to _not_ become a generalized config management tool. It's really quick at what it does _because_ all it does is installs Docker and configures it. I think if extra dependencies or configuration are necessary, users should be pointing at images that have those things baked in, or using cloudinit. As well, I would imagine the `--engine-storage-driver btrfs` option should probably inform the user somehow that it expects various dependencies to be present.

**Comment by ehazlett** [comment]
> There is an explosive amount of docker-machine create flags and this will make the problem worse.  In the future (relatively soon) we want to move to defining machine configuration in a file (#773) to mitigate this problem.

I agree however I think keeping the number of options to a minimum and getting the ability to configure the engine for those is good for now.  But I agree it's rapidly approaching :)

> Where does the line get drawn? That is, when we start discussing allowing the configuration of things like storage drivers, where does Docker Machine's responsibilities lie?

Like you said, for now let's keep this simple.  We will assume the user is using a system that has the support for the options.  Perhaps we could make our "is docker available" check a little better in the event they ask for an option but it's not supported -- that way we could report the actual Engine error instead of a general provisioning error.

> How do we handle multi-args...

Yes, `codegangsta/cli` StringSlice works perfect for this.

:+1: 

@hairyhenderson +1 to tuning the options as well.  i recommended subcommands but as that ticket states, there is a significant UX change involved in that.  I will follow up with more thoughts on that ticket :)

**Comment by wlan0** [comment]
:+1:

**Comment by ibuildthecloud** [comment]
Some of these options concern me.  Obviously I'm looking at this from a RancherOS perspective and some options aren't really configurable in RancherOS.  Like the directory of the graph and the storage driver.  If all of these options were added provisioner would have to support them on a best effort approach.

**Comment by ehazlett** [comment]
@ibuildthecloud thanks for the feedback.  i think in those cases we would fall into the second bullet point where an option was passed but is not supported (we should throw a warn perhaps).  I think it's similar to the case where someone would pass a `--security-opt` but not have selinux enabled or something.  Maybe we would need a capabilities check or something on each provisioner to inform the user if they passed an unsupported option?

**Comment by ibuildthecloud** [comment]
@ehazlett If a provisioner could return a list of a configurable flags that could work.  That could be a maintenance issue though as new flags are added each provisioner would have to change.  Maybe we could return a list of unsupported flags.

**Comment by ehazlett** [comment]
@ibuildthecloud yeah i agree.  i think a list of unsupported would be the route.  thanks!

**Comment by nathanleclaire** [comment]
Yes, @ibuildthecloud an "engine option blacklist" on a per-provisioner basis seems like the best approach to me -- it will need to be maintained in tandem with docs IMO so the users aren't left guessing.  If the provisioner is opinionated about how certain engine options are configured, I'd rather just bomb out than make a best effort / silently configure things other than how we have "promised" etc.

**Comment by arun-gupta** [comment]
Looking forward to a fix for this as this would allow us to specify certificates during machine creation.

**Comment by ehazlett** [comment]
@arun-gupta thanks -- if you are just looking to pass certificates, check the global options - you should be able to do that now.

**Comment by arun-gupta** [comment]
@ehazlett Tried to create the machine as:

```
~> docker-machine --tls-client-cert https://gist.githubusercontent.com/goldmann/66e41f6a7badc23bfebe/raw/8f07c3f5302ce45c4e3ebaadf3e2a09e9876b53f/ca.crt create --driver virtualbox jboss-eap
INFO[0000] Creating client certificate: https://gist.githubusercontent.com/goldmann/66e41f6a7badc23bfebe/raw/8f07c3f5302ce45c4e3ebaadf3e2a09e9876b53f/ca.crt 
FATA[0000] The client key already exists.  Please remove it or specify a different key/cert. 
```

`~/.docker/machine/certs` shows:

```
drwx------  6 arungupta  staff   204 Apr 17 14:04 .
drwx------  5 arungupta  staff   170 Apr 17 14:04 ..
-rw-------  1 arungupta  staff  1679 Apr 17 14:04 ca-key.pem
-rw-r--r--  1 arungupta  staff  1038 Apr 17 14:04 ca.pem
-rw-r--r--  1 arungupta  staff  1062 Apr 17 14:04 cert.pem
-rw-------  1 arungupta  staff  1679 Apr 17 14:04 key.pem
```

Can only one client-cert be used as opposed to storing them in a keystore?

**Comment by ehazlett** [comment]
You cannot use remote files.  It expects them locally.

**Comment by nathanleclaire** [comment]
@ibuildthecloud To follow up on your use case a bit:

Consider that we have a RancherOS provisioner, which does not want to allow users to set the graph dir.  Would throwing an error from the `Provision` step if the provisioner detects that the user is trying to use a custom graph dir be sufficient?  The only issue I can think of is that it can only occur _after_ the machine has actually been created and provisioning has begun, but that's part and parcel with the way provisioners are initialized right now anyway.

**Comment by nathanleclaire** [comment]
This is done
