### ISSUE TITLE
Proposal: RancherOS support

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/machine#992]
At Rancher Labs our goal is that we would really like our "Getting Started" guides for RancherOS to point people to using Docker Machine.  The quick start guide for EC2, for example, would be "Run docker-machine create --amazon..."  @ehazlett has already done most of the heavy lifting to get RancherOS initially working with machine and we would just like to take that work to completion.  Additionally what @ehazlett has already done has identified issues or things in RancherOS that we should fix.

From our analysis it seems that most clouds will work quite easily with a custom RancherOS provisioner (Evan already created the initial version).  RancherOS will be available in all the major clouds soon enough.  The bigger effort is to get RancherOS working with VirtualBox and VMware Fusion (Desktop?).  For those targets I propose the path of least resistance is to just mimic how boot2docker works today.  That means for VirtualBox w/ RancherOS we will support the b2d magic "please format-me" tarball.  I know this approach isn't ideal, but again this is just about getting initial RancherOS support.  We can improve later.  For VMware Fusion we have yet to do the full analysis on how that will work.

One enhancement we see we probably need is the ability for a provisioner to influence driver parameters.  RancherOS is a fast moving target.  Ideally we would like to host something on the internet that you can query to get the lastest version of RancherOS for each cloud.  So AMI for EC2, image for Azure, etc.  We don't want to hard code the AMIs in machine because they change so frequently.  As we get further into this effort I think we can propose a more concrete solution, but at the moment I am merely pointing out a potential issue.

**Comment by ehazlett** [comment]
Thanks for the write up!  I am excited about RancherOS too and I think would be a great option for machine.  I think integration into our provisioning system would be a good path.  I'm not sure about specifics just thinking out loud :)

Very excited to see this :)

**Comment by sthulb** [comment]
+1

**Comment by thaJeztah** [comment]
I hate bare +1s, so, erm, +9 -8?

**Comment by nathanleclaire** [comment]
I'm definitely on board with this.  

> For those targets I propose the path of least resistance is to just mimic how boot2docker works today. That means for VirtualBox w/ RancherOS we will support the b2d magic "please format-me" tarball. I know this approach isn't ideal, but again this is just about getting initial RancherOS support. We can improve later. 

I'm on board with this for a quick fix- as you mention, in the medium-term I think we will need to make handling this more robust.  Not every OS users would want to run locally works like b2d expects to, so I'd definitely be interested to see if we can solve this problem in a general way for RancherOS and, of course, Debian, Ubuntu, CentOS etc.  Naturally, we will need to re-think how some things are named and handled e.g. `--virtualbox-boot2docker-url`

> One enhancement we see we probably need is the ability for a provisioner to influence driver parameters. RancherOS is a fast moving target. Ideally we would like to host something on the internet that you can query to get the lastest version of RancherOS for each cloud. So AMI for EC2, image for Azure, etc. We don't want to hard code the AMIs in machine because they change so frequently. As we get further into this effort I think we can propose a more concrete solution, but at the moment I am merely pointing out a potential issue.

Yeah, this is a little hairy but is something which needs a little love in general.  For the short term parameters which allow you to specify the image name might serve as a workaround (e.g. `docker-machine create -d amazonec2 --amazonec2-ami $(curl rancher.io/images/amazonec2) farm`), since the issue with trying to do it in the provisioner is that OS detection / provisioning doesn't happen until _after_ the instance is already created and booted.  Definitely think there's room for innovation on the issue, and eager to hear what you might have in mind.

**Comment by killerwolf** [comment]
+1
